/**
 * TypeScript declarations for bundled methodology data
 * Auto-generated by bundle-methodologies.ts
 */

export interface BundleMetadata {
  bundled_at: string;
  total_files: number;
  processed_files: number;
  skipped_files: number;
  file_list: string[];
}

export interface BundledMethodologies {
  _metadata: BundleMetadata;
  methodologies: {
    flows?: any;
    processes?: any;
  };
}

declare const bundledMethodologies: BundledMethodologies;
export default bundledMethodologies;