# generated by datamodel-codegen:
#   filename:  tidas_data_types.json
#   timestamp: 2025-10-31T09:15:24+00:00

from __future__ import annotations

from typing import Any, List, Union

from pydantic import AwareDatetime, BaseModel, Field, RootModel, conint, constr


class Model(RootModel[Any]):
    root: Any


class CASNumber(RootModel[constr(pattern=r'^[0-9]{2,7}-[0-9]{2}-[0-9]$')]):
    root: constr(pattern=r'^[0-9]{2,7}-[0-9]{2}-[0-9]$') = Field(
        ..., description='CAS Number, leading zeros are requried.'
    )


class FT(RootModel[str]):
    root: str = Field(..., description='Free text with an unlimited length.')


class StringMultiLangItem(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: constr(max_length=500) = Field(..., alias='#text')


class StringMultiLang1(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: constr(max_length=500) = Field(..., alias='#text')


class StringMultiLang(RootModel[Union[List[StringMultiLangItem], StringMultiLang1]]):
    root: Union[List[StringMultiLangItem], StringMultiLang1] = Field(
        ..., description='Multi-language string with a maximum length of 500 characters'
    )


class Int1(RootModel[constr(pattern=r'^[0-9]$')]):
    root: constr(pattern=r'^[0-9]$') = Field(..., description='1-digit integer number')


class Int5(RootModel[constr(pattern=r'^(0|[1-9]\d{0,4})$')]):
    root: constr(pattern=r'^(0|[1-9]\d{0,4})$') = Field(
        ..., description='5-digit integer number'
    )


class Int6(RootModel[constr(pattern=r'^(0|[1-9]\d{0,5})$')]):
    root: constr(pattern=r'^(0|[1-9]\d{0,5})$') = Field(
        ..., description='6-digit integer number'
    )


class LevelType(RootModel[Int1]):
    root: Int1 = Field(
        ..., description='1-digit integer number, must be equal to or greater than 0'
    )


class Perc(
    RootModel[constr(pattern=r'^(100(\.0{1,3})?|([0-9]|[1-9][0-9])(\.\d{1,3})?)$')]
):
    root: constr(pattern=r'^(100(\.0{1,3})?|([0-9]|[1-9][0-9])(\.\d{1,3})?)$') = Field(
        ..., description='percentage amount'
    )


class MatR(RootModel[str]):
    root: str = Field(..., description='Mathematical rule')


class MatV(RootModel[str]):
    root: str = Field(..., description='Mathematical variable or parameter')


class Real(RootModel[constr(pattern=r'[+-]?(\d+(\.\d*)?|\.\d+)([Ee][+-]?\d+)?$')]):
    root: constr(pattern=r'[+-]?(\d+(\.\d*)?|\.\d+)([Ee][+-]?\d+)?$') = Field(
        ..., description='38-digit real number'
    )


class ST(RootModel[constr(max_length=1000)]):
    root: constr(max_length=1000) = Field(
        ..., description='Short text with a maximum length of 1000 characters'
    )


class String(RootModel[constr(min_length=1, max_length=500)]):
    root: constr(min_length=1, max_length=500) = Field(
        ...,
        description='String with a maximum length of 500 characters. Must have a minimum length of 1.',
    )


class STMultiLangItem(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: constr(max_length=1000) = Field(..., alias='#text')


class STMultiLang1(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: constr(max_length=1000) = Field(..., alias='#text')


class STMultiLang(RootModel[Union[List[STMultiLangItem], STMultiLang1]]):
    root: Union[List[STMultiLangItem], STMultiLang1] = Field(
        ...,
        description='Multi-lang short text with a maximum length of 1000 characters.',
    )


class FTMultiLangItem(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text')


class FTMultiLang1(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text')


class FTMultiLang(RootModel[Union[List[FTMultiLangItem], FTMultiLang1]]):
    root: Union[List[FTMultiLangItem], FTMultiLang1] = Field(
        ..., description='Multi-lang free text with an unlimited length.'
    )


class GlobalReferenceType1(BaseModel):
    field_type: str = Field(..., alias='@type')
    field_refObjectId: constr(
        pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ) = Field(..., alias='@refObjectId')
    field_version: str = Field(..., alias='@version')
    field_uri: str = Field(..., alias='@uri')
    common_shortDescription: STMultiLang = Field(..., alias='common:shortDescription')


class GlobalReferenceTypeItem(BaseModel):
    field_type: str = Field(..., alias='@type')
    field_refObjectId: constr(
        pattern=r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ) = Field(..., alias='@refObjectId')
    field_version: str = Field(..., alias='@version')
    field_uri: str = Field(..., alias='@uri')
    common_shortDescription: STMultiLang = Field(..., alias='common:shortDescription')


class GlobalReferenceType(
    RootModel[Union[GlobalReferenceType1, List[GlobalReferenceTypeItem]]]
):
    root: Union[GlobalReferenceType1, List[GlobalReferenceTypeItem]] = Field(
        ...,
        description='Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.',
    )


class GIS(
    RootModel[
        constr(
            pattern=r'^\s*[+-]?((90(\.0+)?)|([0-8]?\d(\.\d+)?))\s*;\s*[+-]?((180(\.0+)?)|((1[0-7]\d|[0-9]?\d)(\.\d+)?))\s*$'
        )
    ]
):
    root: constr(
        pattern=r'^\s*[+-]?((90(\.0+)?)|([0-8]?\d(\.\d+)?))\s*;\s*[+-]?((180(\.0+)?)|((1[0-7]\d|[0-9]?\d)(\.\d+)?))\s*$'
    ) = Field(
        ...,
        description='Global geographical reference in Latitude and LongitudeExamples: "+42.42;-180", "0;0", "13.22 ; -3"',
    )


class UUID(
    RootModel[
        constr(
            pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        )
    ]
):
    root: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    ) = Field(..., description='Unique Universal Identifier, 16-byte hex number')


class Year(RootModel[conint(ge=1000, le=9999)]):
    root: conint(ge=1000, le=9999) = Field(..., description='4-digit year')


class DateTime(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(
        ..., description='Date and time format acc. to ISO 8601'
    )
