// Generated by ts-to-zod
import { z } from 'zod';

import {
  FTMultiLangSchema,
  GlobalReferenceTypeSchema,
  LevelTypeSchema,
  StringMultiLangSchema,
  UUIDSchema,
} from './tidas_data_types.schema';

export const FlowpropertiesSchema = z.object({
  flowPropertyDataSet: z.object({
    '@xmlns': z.literal('http://lca.jrc.it/ILCD/FlowProperty'),
    '@xmlns:common': z.literal('http://lca.jrc.it/ILCD/Common'),
    '@xmlns:xsi': z.literal('http://www.w3.org/2001/XMLSchema-instance'),
    '@version': z.literal('1.1'),
    '@xsi:schemaLocation': z.literal(
      'http://lca.jrc.it/ILCD/FlowProperty ../../schemas/ILCD_FlowPropertyDataSet.xsd'
    ),
    flowPropertiesInformation: z.object({
      dataSetInformation: z.object({
        'common:UUID': UUIDSchema,
        'common:name': StringMultiLangSchema,
        'common:synonyms': FTMultiLangSchema.optional(),
        classificationInformation: z.object({
          'common:classification': z.object({
            'common:class': z.object({
              '@level': LevelTypeSchema,
              '@classId': z.string(),
              '#text': z.string(),
            }),
            'common:other': z.string().optional(),
          }),
        }),
        'common:generalComment': FTMultiLangSchema.optional(),
        'common:other': z.string().optional(),
      }),
      quantitativeReference: z.object({
        referenceToReferenceUnitGroup: GlobalReferenceTypeSchema,
        'common:other': z.string().optional(),
      }),
      'common:other': z.string().optional(),
    }),
    modellingAndValidation: z
      .object({
        dataSourcesTreatmentAndRepresentativeness: z
          .object({
            referenceToDataSource: GlobalReferenceTypeSchema.optional(),
            'common:other': z.string().optional(),
          })
          .optional(),
        complianceDeclarations: z.object({
          compliance: z.object({
            'common:referenceToComplianceSystem': GlobalReferenceTypeSchema,
            'common:approvalOfOverallCompliance': z.union([
              z.literal('Fully compliant'),
              z.literal('Not compliant'),
              z.literal('Not defined'),
            ]),
          }),
          'common:other': z.string().optional(),
        }),
        'common:other': z.string().optional(),
      })
      .optional(),
    administrativeInformation: z.object({
      dataEntryBy: z.object({
        'common:timeStamp': z.string(),
        'common:referenceToDataSetFormat': GlobalReferenceTypeSchema,
        'common:other': z.string().optional(),
      }),
      publicationAndOwnership: z.object({
        'common:dataSetVersion': z.string(),
        'common:referenceToPrecedingDataSetVersion':
          GlobalReferenceTypeSchema.optional(),
        'common:permanentDataSetURI': z.string().optional(),
        'common:referenceToOwnershipOfDataSet': GlobalReferenceTypeSchema,
        'common:other': z.string().optional(),
      }),
      'common:other': z.string().optional(),
    }),
    'common:other': z.string().optional(),
  }),
});
