"""
TidasLifecyclemodels entity wrapper class for TIDAS SDK. Automatically generated by generate_entity_models.py script. Do not edit this file manually.
To regenerate, run: uv run python scripts/generate_entity_models.py
"""

import datetime
import uuid
from typing import Any, Dict, Optional

from ..core.base import TidasEntity
from ..core.wrappers.lifecyclemodels_wrappers import LifecyclemodelsDataSetWrapper
from ..core.validation import ValidationConfig
from ..types.tidas_lifecyclemodels import Model as LifecyclemodelsModel


class TidasLifecyclemodels(TidasEntity):
    """Wrapper class for Lifecyclemodels entities with pythonic API.

    Represents a lifecyclemodels in LCA.

    Example:
        >>> lifecyclemodels = TidasLifecyclemodels()
        >>> lifecyclemodels.lifecyclemodels_data_set.lifecyclemodels_information.data_set_information.name.set_text(
        ...     "Example Lifecyclemodels", "en"
        ... )
        >>> lifecyclemodels.validate()
    """

    def __init__(
        self,
        data: Optional[Dict[str, Any]] = None,
        validation_config: Optional[ValidationConfig] = None,
    ):
        """Initialize Lifecyclemodels entity.

        Args:
            data: Lifecyclemodels data as dictionary (TIDAS JSON format)
            validation_config: Validation configuration. If None, uses global default.
        """
        super().__init__(data, validation_config)
        self._pydantic_model = LifecyclemodelsModel

        # Initialize default structure if data is empty
        if not self._data:
            self._data = {
                "lifeCycleModelDataSet": {
                    "lifeCycleModelInformation": {
                        "dataSetInformation": {},
                    },
                    "modellingAndValidation": {},
                    "administrativeInformation": {},
                }
            }

    def initialize_defaults(self) -> None:
        """Initialize default values and ensure required structure.

        This method is called during initialization to set up
        required namespace attributes and default field values.
        """
        # IMPORTANT: Ensure nested structure FIRST, then set xmlns fields
        # (ensure_nested_structure overwrites existing values with empty dicts)
        self.ensure_nested_structure([
            "lifeCycleModelDataSet",
            "lifeCycleModelDataSet.lifeCycleModelInformation",
            "lifeCycleModelDataSet.lifeCycleModelInformation.dataSetInformation",
            "lifeCycleModelDataSet.lifeCycleModelInformation.dataSetInformation.classificationInformation",
            "lifeCycleModelDataSet.modellingAndValidation",
            "lifeCycleModelDataSet.administrativeInformation",
            "lifeCycleModelDataSet.administrativeInformation.dataEntryBy",
            "lifeCycleModelDataSet.administrativeInformation.publicationAndOwnership",
        ])

        # Set XML namespace attributes
        self.set_nested_value("lifeCycleModelDataSet.@xmlns", "http://lca.jrc.it/ILCD/LifeCycleModel")
        self.set_nested_value("lifeCycleModelDataSet.@xmlns:common", "http://lca.jrc.it/ILCD/Common")
        self.set_nested_value("lifeCycleModelDataSet.@xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance")
        self.set_nested_value("lifeCycleModelDataSet.@version", "1.1")
        self.set_nested_value("lifeCycleModelDataSet.@xsi:schemaLocation", "http://lca.jrc.it/ILCD/LifeCycleModel ../../schemas/ILCD_LifeCycleModelDataSet.xsd")

    @property
    def lifecyclemodels_data_set(self) -> LifecyclemodelsDataSetWrapper:
        """Access lifeCycleModelDataSet field with IDE autocomplete and type hints.

        This property provides typed access to dataset, enabling
        IDE autocomplete for all nested fields.

        Example:
            >>> lifecyclemodels = TidasLifecyclemodels()
            >>> # IDE shows autocomplete as you type:
            >>> lifecyclemodels.lifecyclemodels_data_set.lifecyclemodels_information.data_set_information.uuid = "..."
        """
        return self._get_typed_field("lifeCycleModelDataSet", LifecyclemodelsDataSetWrapper)

    def to_pydantic(self) -> LifecyclemodelsModel:
        """Convert to Pydantic model for validation and serialization.

        Returns:
            Pydantic model instance with current data
        """
        return self._pydantic_model(**self._data)

    @classmethod
    def from_pydantic(cls, model: LifecyclemodelsModel) -> 'TidasLifecyclemodels':
        """Create entity from Pydantic model.

        Args:
            model: Pydantic model instance

        Returns:
            Entity instance with data from Pydantic model
        """
        return cls(model.model_dump())
