"""
TidasSources entity wrapper class for TIDAS SDK. Automatically generated by generate_entity_models.py script. Do not edit this file manually.
To regenerate, run: uv run python scripts/generate_entity_models.py
"""

import datetime
import uuid
from typing import Any, Dict, Optional

from ..core.base import TidasEntity
from ..core.wrappers.sources_wrappers import SourcesDataSetWrapper
from ..core.validation import ValidationConfig
from ..types.tidas_sources import Model as SourcesModel


class TidasSources(TidasEntity):
    """Wrapper class for Sources entities with pythonic API.

    Represents a sources in LCA.

    Example:
        >>> sources = TidasSources()
        >>> sources.sources_data_set.sources_information.data_set_information.name.set_text(
        ...     "Example Sources", "en"
        ... )
        >>> sources.validate()
    """

    def __init__(
        self,
        data: Optional[Dict[str, Any]] = None,
        validation_config: Optional[ValidationConfig] = None,
    ):
        """Initialize Sources entity.

        Args:
            data: Sources data as dictionary (TIDAS JSON format)
            validation_config: Validation configuration. If None, uses global default.
        """
        super().__init__(data, validation_config)
        self._pydantic_model = SourcesModel

        # Initialize default structure if data is empty
        if not self._data:
            self._data = {
                "sourceDataSet": {
                    "sourcesInformation": {
                        "dataSetInformation": {},
                    },
                    "modellingAndValidation": {},
                    "administrativeInformation": {},
                }
            }

    def initialize_defaults(self) -> None:
        """Initialize default values and ensure required structure.

        This method is called during initialization to set up
        required namespace attributes and default field values.
        """

    @property
    def sources_data_set(self) -> SourcesDataSetWrapper:
        """Access sourceDataSet field with IDE autocomplete and type hints.

        This property provides typed access to dataset, enabling
        IDE autocomplete for all nested fields.

        Example:
            >>> sources = TidasSources()
            >>> # IDE shows autocomplete as you type:
            >>> sources.sources_data_set.sources_information.data_set_information.uuid = "..."
        """
        return self._get_typed_field("sourceDataSet", SourcesDataSetWrapper)

    def to_pydantic(self) -> SourcesModel:
        """Convert to Pydantic model for validation and serialization.

        Returns:
            Pydantic model instance with current data
        """
        return self._pydantic_model(**self._data)

    @classmethod
    def from_pydantic(cls, model: SourcesModel) -> 'TidasSources':
        """Create entity from Pydantic model.

        Args:
            model: Pydantic model instance

        Returns:
            Entity instance with data from Pydantic model
        """
        return cls(model.model_dump())
