# generated by datamodel-codegen:
#   filename:  tidas_sources.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel
from tidas_sdk.types.tidas_sources_category import (
    Sources,
    TidasSourcesText
)

from tidas_sdk.types.tidas_data_types import (
    CASNumber,
    FT,
    FTMultiLang,
    GIS,
    GlobalReferenceType,
    GlobalReferenceTypeOrArray,
    Int1,
    Int5,
    Int6,
    LevelType,
    MatR,
    MatV,
    MultiLangItem,
    MultiLangItemST,
    MultiLangItemString,
    Perc,
    Real,
    ST,
    STMultiLang,
    String,
    StringMultiLang,
    UUID,
    Year
)



class CommonClass(BaseModel):
    field_level: Literal['0'] = Field(..., alias='@level')
    field_classId: Sources = Field(..., alias='@classId')
    text: TidasSourcesText = Field(..., alias='#text')


class CommonClassification(BaseModel):
    common_class: CommonClass = Field(..., alias='common:class')
    common_other: str | None = Field(None, alias='common:other')


class ClassificationInformation(BaseModel):
    """
    Hierachical classification of the Source foreseen to be used to structure the Source content of the database. (Note: This entry is NOT required for the identification of a Source. It should nevertheless be avoided to use identical names for Source in the same class.
    """

    common_classification: CommonClassification = Field(
        ..., alias='common:classification'
    )


class PublicationType(Enum):
    """
    Bibliographic publication type of the source.
    """

    Undefined = 'Undefined'
    Article_in_periodical = 'Article in periodical'
    Chapter_in_anthology = 'Chapter in anthology'
    Monograph = 'Monograph'
    Direct_measurement = 'Direct measurement'
    Oral_communication = 'Oral communication'
    Personal_written_communication = 'Personal written communication'
    Questionnaire = 'Questionnaire'
    Software_or_database = 'Software or database'
    Other_unpublished_and_grey_literature = 'Other unpublished and grey literature'


class ReferenceToDigitalFile(BaseModel):
    """
    Link to a digital file of the source (www-address or intranet-path; relative or absolue path). (Info: Allows direct access to e.g. complete reports of further documentation, which may also be digitally attached to this data set and exchanged jointly with the XML file.)
    """

    field_uri: AnyUrl | None = Field(None, alias='@uri')


class String(RootModel[str]):
    root: str = Field(
        ...,
        description='String with a maximum length of 500 characters. Must have a minimum length of 1.',
        max_length=500,
        min_length=1,
    )


class GIS(RootModel[str]):
    root: str = Field(
        ...,
        description='Global geographical reference in Latitude and LongitudeExamples: "+42.42;-180", "0;0", "13.22 ; -3"',
        pattern='^\\s*[+-]?((90(\\.0+)?)|([0-8]?\\d(\\.\\d+)?))\\s*;\\s*[+-]?((180(\\.0+)?)|((1[0-7]\\d|[0-9]?\\d)(\\.\\d+)?))\\s*$',
    )


class Year(RootModel[int]):
    root: int = Field(..., description='4-digit year', ge=1000, le=9999)


class DataSetInformation(BaseModel):
    common_UUID: str = Field(
        ...,
        alias='common:UUID',
        description='Automatically generated Universally Unique Identifier of this data set. Together with the "Data set version", the UUID uniquely identifies each data set.',
        pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    )
    common_shortName: StringMultiLang = Field(
        ...,
        alias='common:shortName',
        description='Short name for the "Source citation", i.e. for the bibliographical reference or reference to internal data sources used.',
        union_mode='smart',
    )
    classificationInformation: ClassificationInformation = Field(
        ...,
        description='Hierachical classification of the Source foreseen to be used to structure the Source content of the database. (Note: This entry is NOT required for the identification of a Source. It should nevertheless be avoided to use identical names for Source in the same class.',
    )
    sourceCitation: str | None = Field(
        None,
        description='Bibliographical reference or reference to internal data source. Also used in order to reference to databases and tools, data set formats, conformity systems, pictures etc..',
    )
    publicationType: PublicationType | None = Field(
        None, description='Bibliographic publication type of the source.'
    )
    sourceDescriptionOrComment: FTMultiLang | None = Field(
        None,
        description='Free text for additional description of the source. In case of use of published data it may contain a brief summary of the publication and the kind of medium used (e.g. CD-ROM, hard copy).',
        union_mode='smart',
    )
    referenceToDigitalFile: ReferenceToDigitalFile | None = Field(
        None,
        description='Link to a digital file of the source (www-address or intranet-path; relative or absolue path). (Info: Allows direct access to e.g. complete reports of further documentation, which may also be digitally attached to this data set and exchanged jointly with the XML file.)',
    )
    referenceToContact: GlobalReferenceType | list[GlobalReferenceType] | None = (
        Field(
            None,
            description='"Contact data set"s of working groups, organisations or database networks to which EITHER this person or entity OR this database, data set format, or compliance system belongs. [Note: This does not necessarily imply a legally binding relationship, but may also be a voluntary membership.]',
            union_mode='smart',
        )
    )
    referenceToLogo: GlobalReferenceType | list[GlobalReferenceType] | None = (
        Field(
            None,
            description='"Source data set" of the logo of the organisation or source to be used in reports etc.',
            union_mode='smart',
        )
    )
    common_other: str | None = Field(None, alias='common:other')


class SourceInformation(BaseModel):
    dataSetInformation: DataSetInformation
    common_other: str | None = Field(None, alias='common:other')


class DataEntryBy(BaseModel):
    common_timeStamp: AwareDatetime = Field(
        ...,
        alias='common:timeStamp',
        description="Date and time stamp of data set generation, typically an automated entry ('last saved').",
    )
    common_referenceToDataSetFormat: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToDataSetFormat',
        description='"Source data set" of the used version of the ILCD format. If additional data format fields have been integrated into the data set file, using the "namespace" option, the used format namespace(s) are to be given. This is the case if the data sets carries additional information as specified by other, particular LCA formats, e.g. of other database networks or LCA softwares.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class PublicationAndOwnership(BaseModel):
    """
    Information related to publication and version management of the data set including copyright and access restrictions.
    """

    common_dataSetVersion: str = Field(
        ...,
        alias='common:dataSetVersion',
        description='Version number of data set. First two digits refer to major updates, the second two digits to minor revisions and error corrections etc. The third three digits are intended for automatic and internal counting of versions during data set development. Together with the data set\'s UUID, the "Data set version" uniquely identifies each data set.',
    )
    common_referenceToPrecedingDataSetVersion: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToPrecedingDataSetVersion',
        description='Last preceding data set, which was replaced by this version. Either a URI of that data set (i.e. an internet address) or its UUID plus version number is given (or both).',
        union_mode='smart',
    )
    common_permanentDataSetURI: AnyUrl | None = Field(
        None,
        alias='common:permanentDataSetURI',
        description="URI (i.e. an internet address) of the original of this data set. [Note: This equally globally unique identifier supports users and software tools to identify and retrieve the original version of a data set via the internet or to check for available updates. The URI must not represent an existing WWW address, but it should be unique and point to the data access point, e.g. by combining the data owner's www path with the data set's UUID, e.g. http://www.mycompany.com/lca/processes/50f12420-8855-12db-b606-0900210c9a66.]",
    )
    common_referenceToOwnershipOfDataSet: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToOwnershipOfDataSet',
        description='"Contact data set" of the person or entity who owns this data set. (Note: this is not necessarily the publisher of the data set.)',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class AdministrativeInformation(BaseModel):
    """
    Information on data set management and administration.
    """

    dataEntryBy: DataEntryBy
    publicationAndOwnership: PublicationAndOwnership = Field(
        ...,
        description='Information related to publication and version management of the data set including copyright and access restrictions.',
    )
    common_other: str | None = Field(None, alias='common:other')


class SourceDataSet(BaseModel):
    field_xmlns_common: Literal['http://lca.jrc.it/ILCD/Common'] = Field(
        ..., alias='@xmlns:common'
    )
    field_xmlns: Literal['http://lca.jrc.it/ILCD/Source'] = Field(..., alias='@xmlns')
    field_xmlns_xsi: Literal['http://www.w3.org/2001/XMLSchema-instance'] = Field(
        ..., alias='@xmlns:xsi'
    )
    field_version: Literal['1.1'] = Field(..., alias='@version')
    field_xsi_schemaLocation: Literal[
        'http://lca.jrc.it/ILCD/Source ../../schemas/ILCD_SourceDataSet.xsd'
    ] = Field(..., alias='@xsi:schemaLocation')
    sourceInformation: SourceInformation
    administrativeInformation: AdministrativeInformation = Field(
        ..., description='Information on data set management and administration.'
    )
    common_other: str | None = Field(None, alias='common:other')


class Model(BaseModel):
    sourceDataSet: SourceDataSet
