# generated by datamodel-codegen:
#   filename:  tidas_unitgroups.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel
from tidas_sdk.types.tidas_unitgroups_category import (
    TidasUnitgroupsText,
    Unitgroups
)

from tidas_sdk.types.tidas_data_types import (
    CASNumber,
    FT,
    FTMultiLang,
    GIS,
    GlobalReferenceType,
    GlobalReferenceTypeOrArray,
    Int1,
    Int5,
    Int6,
    LevelType,
    MatR,
    MatV,
    MultiLangItem,
    MultiLangItemST,
    MultiLangItemString,
    Perc,
    Real,
    ST,
    STMultiLang,
    String,
    StringMultiLang,
    UUID,
    Year
)



class CommonClass(BaseModel):
    field_level: Literal['0'] = Field(
        ...,
        alias='@level',
        description='If more than one class is specified in a hierachical classification system, the hierarchy level (1,2,...) could be specified with this attribute of class.',
    )
    field_classId: Unitgroups = Field(
        ...,
        alias='@classId',
        description="Unique identifier for the class. [Notes: If such identifiers are also defined in the referenced category file, they should be identical. Identifiers can be UUID's, but also other forms are allowed.]",
    )
    text: TidasUnitgroupsText = Field(..., alias='#text')


class CommonClassification(BaseModel):
    """
    Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.
    """

    common_class: CommonClass = Field(..., alias='common:class')
    common_other: str | None = Field(None, alias='common:other')


class ClassificationInformation(BaseModel):
    """
    Hierachical classification of the Unit groups; foreseen to be used to structure the Unit group content of the database. (Note: This entry is NOT required for the identification of the Unit group data set. It should nevertheless be avoided to use identical names for Unit groups in the same class.
    """

    common_classification: CommonClassification = Field(
        ...,
        alias='common:classification',
        description='Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.',
    )


class CommonApprovalOfOverallCompliance(Enum):
    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class GIS(RootModel[str]):
    root: str = Field(
        ...,
        description='Global geographical reference in Latitude and LongitudeExamples: "+42.42;-180", "0;0", "13.22 ; -3"',
        pattern='^\\s*[+-]?((90(\\.0+)?)|([0-8]?\\d(\\.\\d+)?))\\s*;\\s*[+-]?((180(\\.0+)?)|((1[0-7]\\d|[0-9]?\\d)(\\.\\d+)?))\\s*$',
    )


class Year(RootModel[int]):
    root: int = Field(..., description='4-digit year', ge=1000, le=9999)


class DataSetInformation(BaseModel):
    common_UUID: str = Field(
        ...,
        alias='common:UUID',
        description='Automatically generated Universally Unique Identifier of this data set. Together with the "Data set version", the UUID uniquely identifies each data set.',
        pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    )
    common_name: StringMultiLang = Field(
        ...,
        alias='common:name',
        description='Name of the unit group, typically indicating for which flow property or group of flow properties it is used. The individual units are named in the "Units" section of the "Unit group data set"',
    )
    classificationInformation: ClassificationInformation = Field(
        ...,
        description='Hierachical classification of the Unit groups; foreseen to be used to structure the Unit group content of the database. (Note: This entry is NOT required for the identification of the Unit group data set. It should nevertheless be avoided to use identical names for Unit groups in the same class.',
    )
    common_generalComment: FTMultiLang | None = Field(
        None,
        alias='common:generalComment',
        description='Free text for general information about the data set. E.g. coverage of different unit systems, information sources used, etc.',
    )
    common_other: str | None = Field(None, alias='common:other')


class QuantitativeReference(BaseModel):
    referenceToReferenceUnit: str = Field(
        ..., description='5-digit integer number', pattern='^(0|[1-9]\\d{0,4})$'
    )
    common_other: str | None = Field(None, alias='common:other')


class UnitGroupInformation(BaseModel):
    dataSetInformation: DataSetInformation
    quantitativeReference: QuantitativeReference
    common_other: str | None = Field(None, alias='common:other')


class Compliance(BaseModel):
    """
    One compliance declaration. Multiple declarations may be provided.
    """

    common_referenceToComplianceSystem: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToComplianceSystem',
        description='Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.',
    )
    common_approvalOfOverallCompliance: CommonApprovalOfOverallCompliance = Field(
        ..., alias='common:approvalOfOverallCompliance'
    )
    common_other: str | None = Field(None, alias='common:other')


class Compliance1Item(BaseModel):
    common_referenceToComplianceSystem: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToComplianceSystem',
        description='Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.',
    )
    common_approvalOfOverallCompliance: CommonApprovalOfOverallCompliance = Field(
        ..., alias='common:approvalOfOverallCompliance'
    )
    common_other: str | None = Field(None, alias='common:other')


class Compliance1(RootModel[list[Compliance1Item]]):
    root: list[Compliance1Item] = Field(
        ...,
        description='One compliance declaration. Multiple declarations may be provided.',
        min_length=1,
    )


class ComplianceDeclarations(BaseModel):
    compliance: Compliance | Compliance1 = Field(
        ...,
        description='One compliance declaration. Multiple declarations may be provided.',
    )
    common_other: str | None = Field(None, alias='common:other')


class ModellingAndValidation(BaseModel):
    complianceDeclarations: ComplianceDeclarations
    common_other: str | None = Field(None, alias='common:other')


class DataEntryBy(BaseModel):
    common_timeStamp: AwareDatetime = Field(
        ...,
        alias='common:timeStamp',
        description='Date and time stamp of data set generation, typically an automated entry ("last saved").',
    )
    common_referenceToDataSetFormat: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToDataSetFormat',
        description='"Source data set" of the used version of the ILCD format. If additional data format fields have been integrated into the data set file, using the "namespace" option, the used format namespace(s) are to be given. This is the case if the data sets carries additional information as specified by other, particular LCA formats, e.g. of other database networks or LCA softwares.',
    )
    common_other: str | None = Field(None, alias='common:other')


class PublicationAndOwnership(BaseModel):
    common_dataSetVersion: str = Field(
        ...,
        alias='common:dataSetVersion',
        description='Version number of data set. First two digits refer to major updates, the second two digits to minor revisions and error corrections etc. The third three digits are intended for automatic and internal counting of versions during data set development. Together with the data set\'s UUID, the "Data set version" uniquely identifies each data set.',
    )
    common_referenceToPrecedingDataSetVersion: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToPrecedingDataSetVersion',
        description='Last preceding data set, which was replaced by this version. Either a URI of that data set (i.e. an internet address) or its UUID plus version number is given (or both).',
    )
    common_permanentDataSetURI: AnyUrl | None = Field(
        None,
        alias='common:permanentDataSetURI',
        description="URI (i.e. an internet address) of the original of this data set. [Note: This equally globally unique identifier supports users and software tools to identify and retrieve the original version of a data set via the internet or to check for available updates. The URI must not represent an existing WWW address, but it should be unique and point to the data access point, e.g. by combining the data owner's www path with the data set's UUID, e.g. http://www.mycompany.com/lca/processes/50f12420-8855-12db-b606-0900210c9a66.]",
    )
    common_referenceToOwnershipOfDataSet: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToOwnershipOfDataSet',
        description='"Contact data set" of the person or entity who owns this data set. (Note: this is not necessarily the publisher of the data set.)',
    )
    common_other: str | None = Field(None, alias='common:other')


class AdministrativeInformation(BaseModel):
    dataEntryBy: DataEntryBy
    publicationAndOwnership: PublicationAndOwnership
    common_other: str | None = Field(None, alias='common:other')


class Unit(BaseModel):
    field_dataSetInternalID: str | None = Field(
        None,
        alias='@dataSetInternalID',
        description='5-digit integer number',
        pattern='^(0|[1-9]\\d{0,4})$',
    )
    name: str | None = Field(
        None,
        description='String with a maximum length of 500 characters. Must have a minimum length of 1.',
        max_length=500,
        min_length=1,
    )
    meanValue: str | None = Field(
        None,
        description='38-digit real number',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    generalComment: StringMultiLang | None = Field(
        None,
        description='General comment on each single unit, typically giving the long name and unit system from which this unit stems, and (if necessary) referring to specifc data sources used, or for workflow purposes about status of "finalisation" of an entry etc.',
    )
    common_other: str | None = Field(None, alias='common:other')


class UnitItem(BaseModel):
    field_dataSetInternalID: str | None = Field(
        None,
        alias='@dataSetInternalID',
        description='5-digit integer number',
        pattern='^(0|[1-9]\\d{0,4})$',
    )
    name: str | None = Field(
        None,
        description='String with a maximum length of 500 characters. Must have a minimum length of 1.',
        max_length=500,
        min_length=1,
    )
    meanValue: str | None = Field(
        None,
        description='38-digit real number',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    generalComment: StringMultiLang | None = Field(
        None,
        description='General comment on each single unit, typically giving the long name and unit system from which this unit stems, and (if necessary) referring to specifc data sources used, or for workflow purposes about status of "finalisation" of an entry etc.',
    )


class Units(BaseModel):
    unit: Unit | list[UnitItem] | None = Field(None)
    common_other: str | None = Field(None, alias='common:other')


class UnitGroupDataSet(BaseModel):
    field_xmlns: Literal['http://lca.jrc.it/ILCD/UnitGroup'] = Field(
        ..., alias='@xmlns'
    )
    field_xmlns_common: Literal['http://lca.jrc.it/ILCD/Common'] = Field(
        ..., alias='@xmlns:common'
    )
    field_xmlns_xsi: Literal['http://www.w3.org/2001/XMLSchema-instance'] = Field(
        ..., alias='@xmlns:xsi'
    )
    field_version: Literal['1.1'] = Field(..., alias='@version')
    field_xsi_schemaLocation: Literal[
        'http://lca.jrc.it/ILCD/UnitGroup ../../schemas/ILCD_UnitGroupDataSet.xsd'
    ] = Field(..., alias='@xsi:schemaLocation')
    unitGroupInformation: UnitGroupInformation
    modellingAndValidation: ModellingAndValidation
    administrativeInformation: AdministrativeInformation
    units: Units | None = None
    common_other: str | None = Field(None, alias='common:other')


class Model(BaseModel):
    unitGroupDataSet: UnitGroupDataSet
