# generated by datamodel-codegen:
#   filename:  tidas_lciamethods.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class CommonClas(BaseModel):
    field_level: Literal['0'] = Field(..., alias='@level')
    field_classId: str = Field(..., alias='@classId')
    text: str = Field(..., alias='#text')


class CommonClas1(BaseModel):
    field_level: Literal['1'] = Field(..., alias='@level')
    field_classId: str = Field(..., alias='@classId')
    text: str = Field(..., alias='#text')


class CommonClas2(BaseModel):
    field_level: Literal['2'] = Field(..., alias='@level')
    field_classId: str = Field(..., alias='@classId')
    text: str = Field(..., alias='#text')


class CommonClass1(BaseModel):
    pass


class CommonClassification(BaseModel):
    """
    Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.
    """

    common_class: list[CommonClas | CommonClas1 | CommonClas2] | CommonClass1 = Field(
        ..., alias='common:class'
    )
    common_other: str | None = Field(None, alias='common:other')


class ClassificationInformation(BaseModel):
    common_classification: CommonClassification = Field(
        ...,
        alias='common:classification',
        description='Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.',
    )


class ImpactCategory(Enum):
    """
    Impact category/ies covered by the LCIA method or methodology.
    """

    Climate_change = 'Climate change'
    Ozone_depletion = 'Ozone depletion'
    Terrestrial_Eutrophication = 'Terrestrial Eutrophication'
    Aquatic_Eutrophication = 'Aquatic Eutrophication'
    Acidification = 'Acidification'
    Photochemical_ozone_creation = 'Photochemical ozone creation'
    Land_use = 'Land use'
    Abiotic_resource_depletion = 'Abiotic resource depletion'
    Biotic_resource_depletion = 'Biotic resource depletion'
    Ionizing_radiation = 'Ionizing radiation'
    Cancer_human_health_effects = 'Cancer human health effects'
    Non_cancer_human_health_effects = 'Non-cancer human health effects'
    Respiratory_inorganics = 'Respiratory inorganics'
    Aquatic_eco_toxicity = 'Aquatic eco-toxicity'
    Terrestrial_eco_toxicity = 'Terrestrial eco-toxicity'
    other = 'other'


class AreaOfProtection(Enum):
    """
    For damage (endpoint) and single-point indicators only: Area(s) of Protection the data set relates to.
    """

    Natural_resources = 'Natural resources'
    Natural_environment = 'Natural environment'
    Human_health = 'Human health'
    Other = 'Other'


class TypeOfDataSet(Enum):
    """
    Type of data set regarding the extent of the impact chain that is covered.
    """

    Inventory_indicator = 'Inventory indicator'
    Mid_point_indicator = 'Mid-point indicator'
    Damage_indicator = 'Damage indicator'
    Area_of_Protection_damage_indicator = 'Area of Protection damage indicator'
    Combined_single_point_indicator = 'Combined single-point indicator'
    LCIA_methodology_documentation = 'LCIA methodology documentation'


class LCIAMethodPrinciple(Enum):
    """
    LCIA method principle(s) followed to derive the impact factors.
    """

    Distance_to_target = 'Distance-to-target'
    Critical_surface_time = 'Critical surface-time'
    Effective_volumes = 'Effective volumes'
    AoP_Damage_model = 'AoP-Damage model'
    Carrying_capacity = 'Carrying capacity'
    Resource_dissipation = 'Resource dissipation'
    other = 'other'


class Normalisation(Enum):
    """
    Indication whether or not a normalisation step was included in the resulting impact factors.
    """

    true = 'true'
    false = 'false'


class Weighting(Enum):
    """
    Indication whether or not a weighting-step was included in the resulting impact factors.
    """

    true = 'true'
    false = 'false'


class FieldType(Enum):
    Dependent_internal_review = 'Dependent internal review'
    Independent_internal_review = 'Independent internal review'
    Independent_external_review = 'Independent external review'
    Accredited_third_party_review = 'Accredited third party review'
    Independent_review_panel = 'Independent review panel'
    Not_reviewed = 'Not reviewed'


class FieldName(Enum):
    Raw_data = 'Raw data'
    Unit_process_es___single_operation = 'Unit process(es), single operation'
    Unit_process_es___black_box = 'Unit process(es), black box'
    LCI_results_or_Partly_terminated_system = 'LCI results or Partly terminated system'
    LCIA_results = 'LCIA results'
    Documentation = 'Documentation'
    Life_cycle_inventory_methods = 'Life cycle inventory methods'
    LCIA_results_calculation = 'LCIA results calculation'
    Goal_and_scope_definition = 'Goal and scope definition'


class FieldName1(Enum):
    Validation_of_data_sources = 'Validation of data sources'
    Sample_tests_on_calculations = 'Sample tests on calculations'
    Energy_balance = 'Energy balance'
    Element_balance = 'Element balance'
    Cross_check_with_other_source = 'Cross-check with other source'
    Cross_check_with_other_data_set = 'Cross-check with other data set'
    Expert_judgement = 'Expert judgement'
    Mass_balance = 'Mass balance'
    Compliance_with_legal_limitsRegulated_Inputs_and_Outputs_e_g__emission_data_are_validated_for_compliance_with_legal_limits__typically_after_relating_and_scaling_the_data_to_the_regulated_processes_sites_etc_ = 'Compliance with legal limitsRegulated Inputs and Outputs e.g. emission data are validated for compliance with legal limits, typically after relating and scaling the data to the regulated processes/sites etc.'
    Compliance_with_ISO_14040_to_14044 = 'Compliance with ISO 14040 to 14044'
    Documentation = 'Documentation'
    Evidence_collection_by_means_of_plant_visits_and_or_interviews = (
        'Evidence collection by means of plant visits and/or interviews'
    )


class CommonMethod(BaseModel):
    """
    Validation method(s) used in the respective "Scope of review".
    """

    field_name: FieldName1 = Field(..., alias='@name')


class CommonMethodItem(BaseModel):
    field_name: FieldName1 = Field(..., alias='@name')


class CommonScope(BaseModel):
    """
    Scope of review regarding which aspects and components of the data set was reviewed or verified. In case of aggregated e.g. LCI results also and on which level of detail (e.g. LCI results only, included unit processes, ...) the review / verification was performed.
    """

    field_name: FieldName = Field(..., alias='@name')
    common_method: CommonMethod | list[CommonMethodItem] = Field(
        ...,
        alias='common:method',
        description='Validation method(s) used in the respective "Scope of review".',
        union_mode='smart',
    )


CommonMethod1 = CommonMethod


CommonMethodItem1 = CommonMethodItem


class CommonScopeItem(BaseModel):
    field_name: FieldName = Field(..., alias='@name')
    common_method: CommonMethod1 | list[CommonMethodItem1] = Field(
        ...,
        alias='common:method',
        description='Validation method(s) used in the respective "Scope of review".',
        union_mode='smart',
    )


class CommonApprovalOfOverallCompliance(Enum):
    """
    Official approval whether or not and in how far the data set meets all the requirements of the "Compliance system" refered to. This approval should be issued/confirmed by the owner of that compliance system, who is identified via the respective "Contact data set".
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CommonNomenclatureCompliance(Enum):
    """
    Nomenclature compliance of this data set with the respective requirements set by the "compliance system" refered to.
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CommonMethodologicalCompliance(Enum):
    """
    Methodological compliance of this data set with the respective requirements set by the "compliance system" refered to.
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CommonReviewCompliance(Enum):
    """
    Review/Verification compliance of this data set with the respective requirements set by the "compliance system" refered to.
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CommonDocumentationCompliance(Enum):
    """
    Documentation/Reporting compliance of this data set with the respective requirements set by the "compliance system" refered to.
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CommonQualityCompliance(Enum):
    """
    Quality compliance of this data set with the respective requirements set by the "compliance system" refered to.
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class Level(Enum):
    """
    Level of recommendation given to this data set by the recommending governmental body. Note that the recommendation level of individual elementary flows can be different (lower) from the general level; this is documented as "Deviating recommendation" in the section "Characterisation factors" directly for each affected elementary flow.
    """

    Level_I = 'Level I'
    Level_II = 'Level II'
    Level_III = 'Level III'
    Interim = 'Interim'
    Not_recommended = 'Not recommended'


class CommonWorkflowAndPublicationStatus(Enum):
    """
    Workflow or publication status of data set. Details e.g. of foreseen publication dates should be provided on request by the "Data set owner".
    """

    Working_draft = 'Working draft'
    Final_draft_for_internal_review = 'Final draft for internal review'
    Final_draft_for_external_review = 'Final draft for external review'
    Data_set_finalised__unpublished = 'Data set finalised; unpublished'
    Under_revision = 'Under revision'
    Withdrawn = 'Withdrawn'
    Data_set_finalised__subsystems_published = (
        'Data set finalised; subsystems published'
    )
    Data_set_finalised__entirely_published = 'Data set finalised; entirely published'


class CommonCopyright(Enum):
    """
    Indicates whether or not a copyright on the data set exists. Decided upon by the "Owner of data set". [Note: See also field "Access and use restrictions".]
    """

    true = 'true'
    false = 'false'


class ExchangeDirection(Enum):
    """
    Direction of exchange; this information refers to the entry within the same field in the "Process data set".
    """

    Input = 'Input'
    Output = 'Output'


class UncertaintyDistributionType(Enum):
    """
    Defines the kind of uncertainty distribution that is valid for this particular object or parameter.
    """

    undefined = 'undefined'
    log_normal = 'log-normal'
    normalisation = 'normalisation'
    triangular = 'triangular'
    uniform = 'uniform'


class DataDerivationTypeStatus(Enum):
    """
    Identifies the way by which the individual Input / Output amount was derived (e.g. measured, estimated etc.), respectively the status and relevancy of missing data.
    """

    Measured = 'Measured'
    Calculated = 'Calculated'
    Estimated = 'Estimated'
    Unknown_derivation = 'Unknown derivation'
    Missing_important = 'Missing important'
    Missing_unimportant = 'Missing unimportant'


class DeviatingRecommendation(Enum):
    """
    Deviating (downgraded) recommendation level for this exchange, in reference to the recommendation level of the LCIA method data set as a whole (see field "Official recommendation of data set by governmental body:").
    """

    Level_I = 'Level I'
    Level_II = 'Level II'
    Level_III = 'Level III'
    Interim = 'Interim'
    Not_recommended = 'Not recommended'


class CASNumber(RootModel[str]):
    root: str = Field(
        ...,
        description='CAS Number, leading zeros are requried.',
        pattern='^[0-9]{2,7}-[0-9]{2}-[0-9]$',
    )


class FT(RootModel[str]):
    root: str = Field(..., description='Free text with an unlimited length.')


class StringMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=500)


class StringMultiLang1(RootModel[list[StringMultiLang1Item]]):
    root: list[StringMultiLang1Item] = Field(
        ..., description='Multi-language string with a maximum length of 500 characters'
    )


class StringMultiLang2(BaseModel):
    """
    Multi-language string with a maximum length of 500 characters
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=500)


class Int5(RootModel[str]):
    root: str = Field(
        ..., description='5-digit integer number', pattern='^(0|[1-9]\\d{0,4})$'
    )


class LevelType(RootModel[str]):
    root: str = Field(
        ...,
        description='1-digit integer number, must be equal to or greater than 0',
        pattern='^[0-9]$',
    )


class MatR(RootModel[str]):
    root: str = Field(..., description='Mathematical rule')


class MatV(RootModel[str]):
    root: str = Field(..., description='Mathematical variable or parameter')


class STMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=1000)


class STMultiLang1(RootModel[list[STMultiLang1Item]]):
    root: list[STMultiLang1Item] = Field(
        ...,
        description='Multi-lang short text with a maximum length of 1000 characters.',
    )


class STMultiLang2(BaseModel):
    """
    Multi-lang short text with a maximum length of 1000 characters.
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=1000)


class FTMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text')


class FTMultiLang1(RootModel[list[FTMultiLang1Item]]):
    root: list[FTMultiLang1Item] = Field(
        ..., description='Multi-lang free text with an unlimited length.'
    )


class FTMultiLang2(BaseModel):
    """
    Multi-lang free text with an unlimited length.
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text')


class GlobalReferenceType1(BaseModel):
    """
    Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.
    """

    field_type: str = Field(..., alias='@type')
    field_refObjectId: str = Field(
        ...,
        alias='@refObjectId',
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )
    field_version: str = Field(..., alias='@version')
    field_uri: str = Field(..., alias='@uri')
    common_shortDescription: STMultiLang1 | STMultiLang2 = Field(
        ...,
        alias='common:shortDescription',
        description='Multi-lang short text with a maximum length of 1000 characters.',
        union_mode='smart',
    )


class GlobalReferenceTypeItem(BaseModel):
    field_type: str = Field(..., alias='@type')
    field_refObjectId: str = Field(
        ...,
        alias='@refObjectId',
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )
    field_version: str = Field(..., alias='@version')
    field_uri: str = Field(..., alias='@uri')
    common_shortDescription: STMultiLang1 | STMultiLang2 = Field(
        ...,
        alias='common:shortDescription',
        description='Multi-lang short text with a maximum length of 1000 characters.',
        union_mode='smart',
    )


class Year(RootModel[int]):
    root: int = Field(..., description='4-digit year', ge=1000, le=9999)


class DataSetInformation(BaseModel):
    common_UUID: str = Field(
        ...,
        alias='common:UUID',
        description='Unique identifier of the data set. The UUID is a 128-bit number represented as a hexadecimal string of the form: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. The UUID is used to uniquely identify the data set in the ILCD database.',
        pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    )
    common_name: StringMultiLang1 | StringMultiLang2 = Field(
        ...,
        alias='common:name',
        description='Name of the data set. Composed as follows "LCIA methodology short name; Impact category/ies; midpoint/endpoint; Impact indicator; Source short name". Not applicable components are left out. Examples: "Impacts2007+; Climate change; midpoint; Global Warming Potential; IPCC 2001"; "ABC 2006; Acidification; endpoint; Species diversity loss; John Doe 2006"; "My-indicator2009; combined; endpoint; Ecopoints; various"',
        union_mode='smart',
    )
    methodology: str | None = Field(
        None,
        description='Name of the LCIA methodology/ies the data set belongs to, if any',
    )
    classificationInformation: ClassificationInformation
    impactCategory: ImpactCategory | None = Field(
        None,
        description='Impact category/ies covered by the LCIA method or methodology.',
    )
    areaOfProtection: AreaOfProtection | None = Field(
        None,
        description='For damage (endpoint) and single-point indicators only: Area(s) of Protection the data set relates to.',
    )
    impactIndicator: str | None = Field(
        None,
        description='Description of the meaning of the impact indicator of this data set (not applicable for LCIA methodologies data sets).',
        max_length=500,
        min_length=1,
    )
    common_generalComment: FTMultiLang1 | FTMultiLang2 | None = Field(
        None,
        alias='common:generalComment',
        description='General information about the data set, including e.g. general (internal, not reviewed) quality statements as well as information sources used. (Note: Please also check the more specific fields e.g. on "Intended application", "Advice on data set use" and the fields in the "Modelling and validation" section to avoid overlapping entries.)',
        union_mode='smart',
    )
    referenceToExternalDocumentation: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='"Source data set(s)" of external documents / files with further documentative information on the data set including on underlying data sources (e.g. time, geographical coverage, impact models, characterisation factors, substance property databases employed, etc.). (Note: can indirectly reference to digital file.)',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class QuantitativeReference(BaseModel):
    """
    This section allows to refer to the LCIA method(ology)'s quantitative reference, which is always the unit, in which the characterisation factors of the impact indicator are measured, e.g. "kg CO2-Equivalents".
    """

    referenceQuantity: GlobalReferenceType1 | list[GlobalReferenceTypeItem] = Field(
        ...,
        description='"Flow property data set" of the reference quantity (flow property), in which the impact indicator values are measured.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class Time(BaseModel):
    referenceYear: STMultiLang1 | STMultiLang2 = Field(
        ...,
        description='Reference year when the emission is assumed to take place, i.e. the start year of the time period for which the impact is modelled. For time-independent models "time independent" should be stated.',
        union_mode='smart',
    )
    duration: STMultiLang1 | STMultiLang2 = Field(
        ...,
        description='Time period for which the impact is modelled.',
        union_mode='smart',
    )
    timeRepresentativenessDescription: FTMultiLang1 | FTMultiLang2 = Field(
        ...,
        description='Description of the valid time span of the data set including information on limited usability within sub-time spans, if any.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class InterventionLocation(BaseModel):
    """
    Specific, country, or region of the elementary flows' / exchanges' occurence for which the LCIA method(ology) is valid / modelled. [Note: Entry can be of type "two-letter ISO 3166 country code" for countries, "seven-letter regional codes" for regions or continents, or "market areas and market organisations", as predefined for the ILCD. Also a name for e.g. a specific plant etc. can be given here (e.g. "FR, Lyon, XY Company, Z Site"; user defined). ]
    """

    text: str | None = Field(None, alias='#text')
    field_latitudeAndLongitude: str | None = Field(
        None,
        alias='@latitudeAndLongitude',
        description='Geographical latitude and longitude reference of "Location" / "Sub-location". For area-type locations (e.g. countries, continents) the field is empty.',
        pattern='^\\s*[+-]?((90(\\.0+)?)|([0-8]?\\d(\\.\\d+)?))\\s*;\\s*[+-]?((180(\\.0+)?)|((1[0-7]\\d|[0-9]?\\d)(\\.\\d+)?))\\s*$',
    )


class IntervensionSubLocation(BaseModel):
    """
    Geographical sub-unit(s) of "Intervention location(s)" that further specify the specifically modelled sub-locations. Such sub-locations can be e.g. sites of a company, specific catchments modleled, countries of a continent, or locations in a country. Information on limited representativeness should be provided if applicable.
    """

    text: str | None = Field(None, alias='#text')
    field_latitudeAndLongitude: str | None = Field(
        None,
        alias='@latitudeAndLongitude',
        description='Geographical latitude and longitude reference of "Location" / "Sub-location". For area-type locations (e.g. countries, continents) the field is empty.',
        pattern='^\\s*[+-]?((90(\\.0+)?)|([0-8]?\\d(\\.\\d+)?))\\s*;\\s*[+-]?((180(\\.0+)?)|((1[0-7]\\d|[0-9]?\\d)(\\.\\d+)?))\\s*$',
    )


class ImpactLocation(BaseModel):
    """
    Location or region where the impact is modelled to take place. [Note: Entry can be of type "two-letter ISO 3166 country code" for countries, "seven-letter regional codes" for regions or continents, or "market areas and market organisations", as predefined for the ILCD. Also a name for e.g. a specific catchment etc. can be given here, user defined).]
    """

    text: str | None = Field(None, alias='#text')
    field_latitudeAndLongitude: str | None = Field(
        None,
        alias='@latitudeAndLongitude',
        description='Geographical latitude and longitude reference of "Location" / "Sub-location". For area-type locations (e.g. countries, continents) the field is empty.',
        pattern='^\\s*[+-]?((90(\\.0+)?)|([0-8]?\\d(\\.\\d+)?))\\s*;\\s*[+-]?((180(\\.0+)?)|((1[0-7]\\d|[0-9]?\\d)(\\.\\d+)?))\\s*$',
    )


class Geography(BaseModel):
    interventionLocation: InterventionLocation | str | None = Field(
        None,
        description='Specific, country, or region of the elementary flows\' / exchanges\' occurence for which the LCIA method(ology) is valid / modelled. [Note: Entry can be of type "two-letter ISO 3166 country code" for countries, "seven-letter regional codes" for regions or continents, or "market areas and market organisations", as predefined for the ILCD. Also a name for e.g. a specific plant etc. can be given here (e.g. "FR, Lyon, XY Company, Z Site"; user defined). ]',
        union_mode='smart',
    )
    intervensionSubLocation: IntervensionSubLocation | str | None = Field(
        None,
        description='Geographical sub-unit(s) of "Intervention location(s)" that further specify the specifically modelled sub-locations. Such sub-locations can be e.g. sites of a company, specific catchments modleled, countries of a continent, or locations in a country. Information on limited representativeness should be provided if applicable.',
        union_mode='smart',
    )
    impactLocation: ImpactLocation | str | None = Field(
        None,
        description='Location or region where the impact is modelled to take place. [Note: Entry can be of type "two-letter ISO 3166 country code" for countries, "seven-letter regional codes" for regions or continents, or "market areas and market organisations", as predefined for the ILCD. Also a name for e.g. a specific catchment etc. can be given here, user defined).]',
        union_mode='smart',
    )
    geographicalRepresentativenessDescription: FTMultiLang1 | FTMultiLang2 | None = (
        Field(
            None,
            description='Further explanation on additional aspects of the location, both regarding the intervention and the impact: whether certain areas are exempted from the location, whether data is only valid for certain sub-locations within the location indicated, or whether impact indicator values for certain elementary flows are extrapolated from another geographical area than indicated. Information on the use of generic intervention and/or impact locations, and other restrictions.',
            union_mode='smart',
        )
    )
    common_other: str | None = Field(None, alias='common:other')


class ImpactModel(BaseModel):
    """
    Provides information about the general representativiness of the data set and about its composition of single LCIA-methods.
    """

    modelName: str = Field(
        ...,
        description='Name(s) of the model(s) used for calculating the LCIA impact indicator values (if any)',
        max_length=1000,
    )
    modelDescription: FTMultiLang1 | FTMultiLang2 = Field(
        ...,
        description='Description of the model used for calculating the LCIA impact indicator values, including underlying substance property data sources, background concentrations, etc. If an LCIA methodology comprises several LCIA methods, these are explicitly included in the description. Professional nomenclature is used for the description. Note that eventually included Normalisation and Weighting factors are described in the dedicated separate fields.',
        union_mode='smart',
    )
    referenceToModelSource: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='"Source data set(s)" of data sources concerning the characterisation model (guidelines, supporting documentation etc)',
        union_mode='smart',
    )
    referenceToIncludedMethods: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='"LCIA method data set(s)" of LCIA characterisation methods included in this data set or used to derive this LCIA methodology',
        union_mode='smart',
    )
    consideredMechanisms: STMultiLang1 | STMultiLang2 | None = Field(
        None,
        description='Description of the environmental or other mechanisms included in the explicitly considered part of the impact chain. Can relate to (ilustrative): For emissions e.g.: transport, conversion / degradation, exposure, effect(s), damage(s) on humans and the natural environment. For material and energy resources: scarcity or other impact concept. For land use: soil, area, biocoenosis related meachanisms, effect(s), damage(s).',
        union_mode='smart',
    )
    referenceToMethodologyFlowChart: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='"Source data set(s)" of flowchart(s) and/or pictures depicting the LCIA method(ology).',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class LCIAMethodInformation(BaseModel):
    dataSetInformation: DataSetInformation
    quantitativeReference: QuantitativeReference = Field(
        ...,
        description='This section allows to refer to the LCIA method(ology)\'s quantitative reference, which is always the unit, in which the characterisation factors of the impact indicator are measured, e.g. "kg CO2-Equivalents".',
    )
    time: Time
    geography: Geography | None = None
    impactModel: ImpactModel = Field(
        ...,
        description='Provides information about the general representativiness of the data set and about its composition of single LCIA-methods.',
    )
    common_other: str | None = Field(None, alias='common:other')


class LCIAMethodNormalisationAndWeighting(BaseModel):
    """
    LCIA methodological modelling aspects
    """

    typeOfDataSet: TypeOfDataSet = Field(
        ...,
        description='Type of data set regarding the extent of the impact chain that is covered.',
    )
    LCIAMethodPrinciple_1: LCIAMethodPrinciple = Field(
        ...,
        alias='LCIAMethodPrinciple',
        description='LCIA method principle(s) followed to derive the impact factors.',
    )
    deviationsFromLCIAMethodPrinciple: FTMultiLang1 | FTMultiLang2 | None = Field(
        None,
        description='Short description of possible data set specific deviations from "LCIA method principle(s)". Refers especially to explanations on the combination of LCIA methods with different principles in a single LCIA methodology.',
        union_mode='smart',
    )
    normalisation: Normalisation | None = Field(
        None,
        description='Indication whether or not a normalisation step was included in the resulting impact factors.',
    )
    referenceToUsableNormalisationDataSets: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='"Normalisation data sets" that can be used together with the impact factors of this data set.',
        union_mode='smart',
    )
    normalisationDescription: STMultiLang1 | STMultiLang2 | None = Field(
        None,
        description='Short description of the included normalisation, if any.',
        union_mode='smart',
    )
    referenceToIncludedNormalisationDataSets: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='"Normalisation data set(s)" that was/were used to calculate the normalised impact factors of this data set, if any.',
        union_mode='smart',
    )
    weighting: Weighting | None = Field(
        None,
        description='Indication whether or not a weighting-step was included in the resulting impact factors.',
    )
    referenceToUsableWeightingDataSets: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='"Weighting data set(s)", that can be used together with the impact factors of this data set.',
        union_mode='smart',
    )
    weightingDescription: STMultiLang1 | STMultiLang2 | None = Field(
        None,
        description='Short description of the included weighting, if any.',
        union_mode='smart',
    )
    referenceToIncludedWeightingDataSets: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='"Weighting data set" that was used to calculate the weighted impact factors of this data set, if any.',
        union_mode='smart',
    )


class DataSources(BaseModel):
    """
    Data sources used for the model and the underlying substance and other data.
    """

    referenceToDataSource: GlobalReferenceType1 | list[GlobalReferenceTypeItem] = Field(
        ...,
        description='"Source data set(s)" of the data source(s) used for the data set e.g. paper, questionnaire, monography etc. The main data sources e.g. for underlying substance properties are named, too.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class Completeness(BaseModel):
    completenessImpactCoverage: str | None = Field(
        None,
        description='Estimate of the completeness of coverage of impact(s), as identified in the fields "Impact category/ies" or - only for LCIA methodologies with Damage indicator or Combined single-point indicators - "Area(s) of Protection". Expressed by the quantitative extent of coverage of the scientifically recognized, impact. Note that this information is typically highly uncertain.',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )
    inventoryItems: str | None = Field(
        None,
        description='Number of chemical substances/substance groups, chemical elements, or types covered, without considering variants by environmental emission or source compartment, geographical location, time, or other.',
        pattern='^(0|[1-9]\\d{0,5})$',
    )


class Review(BaseModel):
    """
    Type of review that has been performed regarding independency and type of review process.
    """

    field_type: FieldType = Field(..., alias='@type')
    common_scope: CommonScope | list[CommonScopeItem] | None = Field(
        None,
        alias='common:scope',
        description='Scope of review regarding which aspects and components of the data set was reviewed or verified. In case of aggregated e.g. LCI results also and on which level of detail (e.g. LCI results only, included unit processes, ...) the review / verification was performed.',
        union_mode='smart',
    )
    common_reviewDetails: FTMultiLang1 | FTMultiLang2 | None = Field(
        None,
        alias='common:reviewDetails',
        description='Summary of the review. All the following items should be explicitly addressed: completeness and appropriateness of the model, geographical and temporal coverage and differentiation, correctness and precision of substance data or other underlying data; appropriateness and coherence of application of normalisation and/or weighting schemes, if included; correctness, appropriateness, comprehensibility, and completeness of the data set documentation; stakeholder aceptance of LCIA method. Optional: Comment of the reviewer on characterisation factors for single elementary flows or groups of elementary flows. Relevant restrictions to the review due to lack of transparency or documentation should be named. An overall quality statement may be included here.',
        union_mode='smart',
    )
    common_referenceToNameOfReviewerAndInstitution: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        alias='common:referenceToNameOfReviewerAndInstitution',
        description='"Contact data set" of reviewer. The full name of reviewer(s) and institution(s) as well as a contact address and/or email should be provided in that contact data set.',
        union_mode='smart',
    )
    common_otherReviewDetails: FTMultiLang1 | FTMultiLang2 | None = Field(
        None,
        alias='common:otherReviewDetails',
        description='Further information from the review process, especially comments received from third parties once the data set has been published or additional reviewer comments from an additional external review.',
        union_mode='smart',
    )
    common_referenceToCompleteReviewReport: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        alias='common:referenceToCompleteReviewReport',
        description='"Source data set" of the complete review report.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class Validation(BaseModel):
    """
    Review information on LCIA method.
    """

    review: Review = Field(
        ...,
        description='Type of review that has been performed regarding independency and type of review process.',
    )
    common_other: str | None = Field(None, alias='common:other')


class Compliance(BaseModel):
    """
    One compliance declaration. Multiple declarations may be provided.
    """

    common_referenceToComplianceSystem: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToComplianceSystem',
        description='"Source data set" of the "Compliance system" that is declared to be met by the data set.',
        union_mode='smart',
    )
    common_approvalOfOverallCompliance: CommonApprovalOfOverallCompliance = Field(
        ...,
        alias='common:approvalOfOverallCompliance',
        description='Official approval whether or not and in how far the data set meets all the requirements of the "Compliance system" refered to. This approval should be issued/confirmed by the owner of that compliance system, who is identified via the respective "Contact data set".',
    )
    common_nomenclatureCompliance: CommonNomenclatureCompliance = Field(
        ...,
        alias='common:nomenclatureCompliance',
        description='Nomenclature compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_methodologicalCompliance: CommonMethodologicalCompliance = Field(
        ...,
        alias='common:methodologicalCompliance',
        description='Methodological compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_reviewCompliance: CommonReviewCompliance = Field(
        ...,
        alias='common:reviewCompliance',
        description='Review/Verification compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_documentationCompliance: CommonDocumentationCompliance = Field(
        ...,
        alias='common:documentationCompliance',
        description='Documentation/Reporting compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_qualityCompliance: CommonQualityCompliance = Field(
        ...,
        alias='common:qualityCompliance',
        description='Quality compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_other: str | None = Field(None, alias='common:other')


class Compliance1Item(BaseModel):
    common_referenceToComplianceSystem: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToComplianceSystem',
        description='"Source data set" of the "Compliance system" that is declared to be met by the data set.',
        union_mode='smart',
    )
    common_approvalOfOverallCompliance: CommonApprovalOfOverallCompliance = Field(
        ...,
        alias='common:approvalOfOverallCompliance',
        description='Official approval whether or not and in how far the data set meets all the requirements of the "Compliance system" refered to. This approval should be issued/confirmed by the owner of that compliance system, who is identified via the respective "Contact data set".',
    )
    common_nomenclatureCompliance: CommonNomenclatureCompliance = Field(
        ...,
        alias='common:nomenclatureCompliance',
        description='Nomenclature compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_methodologicalCompliance: CommonMethodologicalCompliance = Field(
        ...,
        alias='common:methodologicalCompliance',
        description='Methodological compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_reviewCompliance: CommonReviewCompliance = Field(
        ...,
        alias='common:reviewCompliance',
        description='Review/Verification compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_documentationCompliance: CommonDocumentationCompliance = Field(
        ...,
        alias='common:documentationCompliance',
        description='Documentation/Reporting compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_qualityCompliance: CommonQualityCompliance = Field(
        ...,
        alias='common:qualityCompliance',
        description='Quality compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_other: str | None = Field(None, alias='common:other')


class Compliance1(RootModel[list[Compliance1Item]]):
    root: list[Compliance1Item] = Field(
        ...,
        description='One compliance declaration. Multiple declarations may be provided.',
        min_length=1,
    )


class ComplianceDeclarations(BaseModel):
    """
    Statements on compliance of several data set aspects with compliance requirements as defined by the referenced compliance system (e.g. an EPD scheme, handbook of a national or international data network such as the ILCD, etc.).
    """

    compliance: Compliance | Compliance1 = Field(
        ...,
        description='One compliance declaration. Multiple declarations may be provided.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class ModellingAndValidation(BaseModel):
    """
    Covers the five sub-sections 1) LCIA method, normalisation, weighting 2) Data sources 3) Completeness, 4) Validation, and 5) Compliance declarations.
    """

    useAdviceForDataSet: STMultiLang1 | STMultiLang2 | None = Field(
        None,
        description='Methodological advice for the use and application of this data set, such as limits in applicability or representativeness as well as recommendations to use it together with others from the same LCIA methodology to ensure consistency.',
        union_mode='smart',
    )
    LCIAMethodNormalisationAndWeighting_1: LCIAMethodNormalisationAndWeighting = Field(
        ...,
        alias='LCIAMethodNormalisationAndWeighting',
        description='LCIA methodological modelling aspects',
    )
    dataSources: DataSources = Field(
        ...,
        description='Data sources used for the model and the underlying substance and other data.',
    )
    completeness: Completeness | None = None
    validation: Validation = Field(
        ..., description='Review information on LCIA method.'
    )
    complianceDeclarations: ComplianceDeclarations = Field(
        ...,
        description='Statements on compliance of several data set aspects with compliance requirements as defined by the referenced compliance system (e.g. an EPD scheme, handbook of a national or international data network such as the ILCD, etc.).',
    )
    common_other: str | None = Field(None, alias='common:other')


class CommonCommissionerAndGoal(BaseModel):
    """
    Extract of the information items linked to goal and scope of LCIA method modeling.
    """

    common_referenceToCommissioner: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        alias='common:referenceToCommissioner',
        description='"Contact data set" of the commissioner / financing party of the data collection / compilation and of the data set modelling. For groups of commissioners, each single organisation should be named. For data set updates and for direct use of data from formerly commissioned studies, also the original commissioner should be named.',
        union_mode='smart',
    )
    common_project: StringMultiLang1 | StringMultiLang2 | None = Field(
        None,
        alias='common:project',
        description='Extract of the information items linked to goal and scope of LCIA method modeling.',
        union_mode='smart',
    )
    common_intendedApplications: FTMultiLang1 | FTMultiLang2 | None = Field(
        None,
        alias='common:intendedApplications',
        description='Documentation of the intended application(s) of data collection and data set modelling. This indicates / includes information on the level of detail, the specifidity, and the quality ambition in the effort.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class DataGenerator(BaseModel):
    """
    Expert(s), that compiled and modelled the data set as well as internal administrative information linked to the data generation activity.
    """

    common_referenceToPersonOrEntityGeneratingTheDataSet: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToPersonOrEntityGeneratingTheDataSet',
        description='"Contact data set" of the person(s), working group(s), organisation(s) or database network, that generated the data set, i.e. being responsible for its correctness regarding methods, inventory, and documentation.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class RecommendationBy(BaseModel):
    referenceToEntity: GlobalReferenceType1 | list[GlobalReferenceTypeItem] = Field(
        ...,
        description='"Contact data set(s)" of the governmental body/ies that has/ve officially recommended this LCIA method data set and its impact factors for use within the documented scope. Eventually deviating (downgraded) recommendations for individual exchanges are documented in the "Inputs and Outputs" section of the data set.',
        union_mode='smart',
    )
    level: Level = Field(
        ...,
        description='Level of recommendation given to this data set by the recommending governmental body. Note that the recommendation level of individual elementary flows can be different (lower) from the general level; this is documented as "Deviating recommendation" in the section "Characterisation factors" directly for each affected elementary flow.',
    )
    meaning: FTMultiLang1 | FTMultiLang2 = Field(
        ...,
        description='Specific meaning of the declared recommendation level of this LCIA method / methodology and the characterisation factors, as defined in the guidance document referenced in in the field "Compliance system"',
        union_mode='smart',
    )


class DataEntryBy(BaseModel):
    """
    Staff or entity, that documented the generated data set, entering the information into the database; plus administrative information linked to the data entry activity.
    """

    common_timeStamp: AwareDatetime = Field(
        ...,
        alias='common:timeStamp',
        description='Date and time stamp of data set generation, typically an automated entry ("last saved").',
    )
    common_referenceToDataSetFormat: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToDataSetFormat',
        description='"Source data set" of the used version of the ILCD format. If additional data format fields have been integrated into the data set file, using the "namespace" option, the used format namespace(s) are to be given. This is the case if the data sets carries additional information as specified by other, particular LCA formats, e.g. of other database networks or LCA softwares.',
        union_mode='smart',
    )
    common_referenceToConvertedOriginalDataSetFrom: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        alias='common:referenceToConvertedOriginalDataSetFrom',
        description='"Source data set" of the database or data set publication from which this data set has been obtained by conversion. This can cover e.g. conversion to a different format, applying a different nomenclature, mapping of flow names, conversion of units, etc. This may however not have changed or re-modeled the Inputs and Outputs, i.e. obtaining the same LCIA results. This entry is required for converted data sets stemming originally from other LCA databases (e.g. when re-publishing data from IISI, ILCD etc. databases). [Note: Identically re-published data sets are identied in the field "Unchanged re-publication of:" in the section "Publication and Ownership".]',
        union_mode='smart',
    )
    common_referenceToPersonOrEntityEnteringTheData: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        alias='common:referenceToPersonOrEntityEnteringTheData',
        description='"Contact data set" of the responsible person or entity that has documented this data set, i.e. entered the data and the descriptive information.',
        union_mode='smart',
    )
    recommendationBy: RecommendationBy
    common_other: str | None = Field(None, alias='common:other')


class PublicationAndOwnership(BaseModel):
    """
    Information related to publication and version management of the data set including copyright and access restrictions.
    """

    common_dateOfLastRevision: AwareDatetime = Field(
        ...,
        alias='common:dateOfLastRevision',
        description='Date when the data set was revised for the last time, typically manually set.',
    )
    common_dataSetVersion: str = Field(
        ...,
        alias='common:dataSetVersion',
        description='Version number of data set. First two digits refer to major updates, the second two digits to minor revisions and error corrections etc. The third three digits are intended for automatic and internal counting of versions during data set development. Together with the data set\'s UUID, the "Data set version" uniquely identifies each data set.',
    )
    common_referenceToPrecedingDataSetVersion: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        alias='common:referenceToPrecedingDataSetVersion',
        description='Last preceding data set, which was replaced by this version. Either a URI of that data set (i.e. an internet address) or its UUID plus version number is given (or both).',
        union_mode='smart',
    )
    common_permanentDataSetURI: AnyUrl | None = Field(
        None,
        alias='common:permanentDataSetURI',
        description="URI (i.e. an internet address) of the original of this data set. [Note: This equally globally unique identifier supports users and software tools to identify and retrieve the original version of a data set via the internet or to check for available updates. The URI must not represent an existing WWW address, but it should be unique and point to the data access point, e.g. by combining the data owner's www path with the data set's UUID, e.g. http://www.mycompany.com/lca/processes/50f12420-8855-12db-b606-0900210c9a66.]",
    )
    common_workflowAndPublicationStatus: CommonWorkflowAndPublicationStatus | None = (
        Field(
            None,
            alias='common:workflowAndPublicationStatus',
            description='Workflow or publication status of data set. Details e.g. of foreseen publication dates should be provided on request by the "Data set owner".',
        )
    )
    common_referenceToUnchangedRepublication: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        alias='common:referenceToUnchangedRepublication',
        description='"Source data set" of the publication, in which this data set was published for the first time. [Note: This refers to exactly this data set as it is, without any format conversion, adjustments, flow name mapping, etc. In case this data set was modified/converted, the original source is documented in "Converted original data set from:" in section "Data entry by".]',
        union_mode='smart',
    )
    common_referenceToOwnershipOfDataSet: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToOwnershipOfDataSet',
        description='"Contact data set" of the person or entity who owns this data set. (Note: this is not necessarily the publisher of the data set.)',
        union_mode='smart',
    )
    common_copyright: CommonCopyright | None = Field(
        None,
        alias='common:copyright',
        description='Indicates whether or not a copyright on the data set exists. Decided upon by the "Owner of data set". [Note: See also field "Access and use restrictions".]',
    )
    common_accessRestrictions: FTMultiLang1 | FTMultiLang2 | None = Field(
        None,
        alias='common:accessRestrictions',
        description='Access restrictions / use conditions for this data set as free text or referring to e.g. license conditions. In case of no restrictions "None" is entered.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class AdministrativeInformation(BaseModel):
    """
    Information required for data set management and administration.
    """

    common_commissionerAndGoal: CommonCommissionerAndGoal | None = Field(
        None,
        alias='common:commissionerAndGoal',
        description='Extract of the information items linked to goal and scope of LCIA method modeling.',
    )
    dataGenerator: DataGenerator = Field(
        ...,
        description='Expert(s), that compiled and modelled the data set as well as internal administrative information linked to the data generation activity.',
    )
    dataEntryBy: DataEntryBy = Field(
        ...,
        description='Staff or entity, that documented the generated data set, entering the information into the database; plus administrative information linked to the data entry activity.',
    )
    publicationAndOwnership: PublicationAndOwnership = Field(
        ...,
        description='Information related to publication and version management of the data set including copyright and access restrictions.',
    )
    common_other: str | None = Field(None, alias='common:other')


class Factor(BaseModel):
    referenceToFlowDataSet: GlobalReferenceType1 | list[GlobalReferenceTypeItem] = (
        Field(
            ...,
            description='Reference to "UUID of flow" of "Flow data set" to link the particular impact factor in the "LCIA data set" to the respective "Flow data set". Please be aware, that for location-specific LCIA methods, there may be multiple references to the same Flow data set.',
            union_mode='smart',
        )
    )
    location: str | None = Field(
        None,
        description='Location where exchange of elementary flow occurs. Used only for those LCIA methods, that make use of such information. This information refers to the entry within the same field in the "Process data set".',
    )
    exchangeDirection: ExchangeDirection = Field(
        ...,
        description='Direction of exchange; this information refers to the entry within the same field in the "Process data set".',
    )
    meanValue: str = Field(
        ...,
        description='Mean value of the impact characterisation factor for the exchange identified by the fields "Reference to flow data set", "Exchange direction" and "Location of direction". It is recommended to report only significant digits of the amount. ! If for an elementary flow its relevant contribution to this LCIA theme is known by state-of-the-art scientific knowledge, but no impact factor is provided in the LCIA method, the flow should nevertheless be referrenced and the mean value to be entered is "0"!',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    minimumValue: str | None = Field(
        None,
        description='Minimum value of the characterisation factor for the exchange in case uncertainty distribution is uniform or triangular.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    maximumValue: str | None = Field(
        None,
        description='Maximum value of the characterisation factor for the exchange in case uncertainty distribution is uniform or triangular.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    uncertaintyDistributionType: UncertaintyDistributionType | None = Field(
        None,
        description='Defines the kind of uncertainty distribution that is valid for this particular object or parameter.',
    )
    relativeStandardDeviation95In: str | None = Field(
        None,
        description='The resulting overall uncertainty of the calculated variable value considering uncertainty of measurements, modelling, appropriateness etc. [Notes: For log-normal distribution the square of the geometric standard deviation (SDg^2) is stated. Mean value times SDg^2 equals the 97.5% value (= Maximum value), Mean value divided by SDg^2 equals the 2.5% value (= Minimum value). For normal distribution the doubled standard deviation value (2*SD) is entered. Mean value plus 2*SD equals 97.5% value (= Maximum value), Mean value minus 2*SD equals 2.5% value (= Minimum value). This data field remains empty when uniform or triangular uncertainty distribution is applied.]',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )
    dataDerivationTypeStatus: DataDerivationTypeStatus | None = Field(
        None,
        description='Identifies the way by which the individual Input / Output amount was derived (e.g. measured, estimated etc.), respectively the status and relevancy of missing data.',
    )
    deviatingRecommendation: DeviatingRecommendation = Field(
        ...,
        description='Deviating (downgraded) recommendation level for this exchange, in reference to the recommendation level of the LCIA method data set as a whole (see field "Official recommendation of data set by governmental body:").',
    )
    referenceToDataSource: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='Reference to "UUID of source"(s) in the "Source data set" of data source(s) used for modelling the value of this single LCIA factor e.g. a specific paper, questionnaire, monography etc. If, as typical, more than one data source was used, more than one source can be referenced.',
        union_mode='smart',
    )
    generalComment: StringMultiLang1 | StringMultiLang2 | None = Field(
        None,
        description='General information about the data set, including e.g. general (internal, not reviewed) quality statements as well as information sources used. (Note: Please also check the more specific fields e.g. on "Intended application", "Advice on data set use" and the fields in the "Modelling and validation" section to avoid overlapping entries.)',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class ReferenceToDataSource(BaseModel):
    referenceToDataSource: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='Reference to "UUID of source"(s) in the "Source data set" of data source(s) used for modelling the value of this single LCIA factor e.g. a specific paper, questionnaire, monography etc. If, as typical, more than one data source was used, more than one source can be referenced.',
        union_mode='smart',
    )


class FactorItem(BaseModel):
    referenceToFlowDataSet: GlobalReferenceType1 | list[GlobalReferenceTypeItem] = (
        Field(
            ...,
            description='Reference to "UUID of flow" of "Flow data set" to link the particular impact factor in the "LCIA data set" to the respective "Flow data set". Please be aware, that for location-specific LCIA methods, there may be multiple references to the same Flow data set.',
            union_mode='smart',
        )
    )
    location: str | None = Field(
        None,
        description='Location where exchange of elementary flow occurs. Used only for those LCIA methods, that make use of such information. This information refers to the entry within the same field in the "Process data set".',
    )
    exchangeDirection: ExchangeDirection = Field(
        ...,
        description='Direction of exchange; this information refers to the entry within the same field in the "Process data set".',
    )
    meanValue: str = Field(
        ...,
        description='Mean value of the impact characterisation factor for the exchange identified by the fields "Reference to flow data set", "Exchange direction" and "Location of direction". It is recommended to report only significant digits of the amount. ! If for an elementary flow its relevant contribution to this LCIA theme is known by state-of-the-art scientific knowledge, but no impact factor is provided in the LCIA method, the flow should nevertheless be referrenced and the mean value to be entered is "0"!',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    minimumValue: str | None = Field(
        None,
        description='Minimum value of the characterisation factor for the exchange in case uncertainty distribution is uniform or triangular.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    maximumValue: str | None = Field(
        None,
        description='Maximum value of the characterisation factor for the exchange in case uncertainty distribution is uniform or triangular.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    uncertaintyType: UncertaintyDistributionType | None = Field(
        None,
        description='Defines the kind of uncertainty distribution that is valid for this particular object or parameter.',
    )
    relativeStandardDeviation95In: str | None = Field(
        None,
        description='The resulting overall uncertainty of the calculated variable value considering uncertainty of measurements, modelling, appropriateness etc. [Notes: For log-normal distribution the square of the geometric standard deviation (SDg^2) is stated. Mean value times SDg^2 equals the 97.5% value (= Maximum value), Mean value divided by SDg^2 equals the 2.5% value (= Minimum value). For normal distribution the doubled standard deviation value (2*SD) is entered. Mean value plus 2*SD equals 97.5% value (= Maximum value), Mean value minus 2*SD equals 2.5% value (= Minimum value). This data field remains empty when uniform or triangular uncertainty distribution is applied.]',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )
    dataDerivationTypeStatus: DataDerivationTypeStatus | None = Field(
        None,
        description='Identifies the way by which the individual Input / Output amount was derived (e.g. measured, estimated etc.), respectively the status and relevancy of missing data.',
    )
    deviatingRecommendation: DeviatingRecommendation = Field(
        ...,
        description='Deviating (downgraded) recommendation level for this exchange, in reference to the recommendation level of the LCIA method data set as a whole (see field "Official recommendation of data set by governmental body:").',
    )
    referenceToDataSource: ReferenceToDataSource | None = None
    generalComment: StringMultiLang1 | StringMultiLang2 | None = Field(
        None,
        description='General information about the data set, including e.g. general (internal, not reviewed) quality statements as well as information sources used. (Note: Please also check the more specific fields e.g. on "Intended application", "Advice on data set use" and the fields in the "Modelling and validation" section to avoid overlapping entries.)',
        union_mode='smart',
    )


class CharacterisationFactors(BaseModel):
    """
    Flow / Exchanges list with corresponding impact factors according to the respective LCIA method.
    """

    factor: Factor | list[FactorItem] = Field(..., union_mode='smart')
    common_other: str | None = Field(None, alias='common:other')


class LCIAMethodDataSet(BaseModel):
    field_xmlns: Literal['http://lca.jrc.it/ILCD/LCIAMethod'] = Field(
        'http://lca.jrc.it/ILCD/LCIAMethod', alias='@xmlns'
    )
    field_xmlns_common: Literal['http://lca.jrc.it/ILCD/Common'] = Field(
        'http://lca.jrc.it/ILCD/Common', alias='@xmlns:common'
    )
    field_xmlns_xsi: Literal['http://www.w3.org/2001/XMLSchema-instance'] = Field(
        'http://www.w3.org/2001/XMLSchema-instance', alias='@xmlns:xsi'
    )
    field_version: Literal['1.1'] = Field('1.1', alias='@version')
    field_xsi_schemaLocation: Literal[
        'http://lca.jrc.it/ILCD/LCIAMethod ../../schemas/ILCD_LCIAMethodDataSet.xsd'
    ] = Field(
        'http://lca.jrc.it/ILCD/LCIAMethod ../../schemas/ILCD_LCIAMethodDataSet.xsd',
        alias='@xsi:schemaLocation',
    )
    LCIAMethodInformation_1: LCIAMethodInformation = Field(
        ..., alias='LCIAMethodInformation'
    )
    modellingAndValidation: ModellingAndValidation = Field(
        ...,
        description='Covers the five sub-sections 1) LCIA method, normalisation, weighting 2) Data sources 3) Completeness, 4) Validation, and 5) Compliance declarations.',
    )
    administrativeInformation: AdministrativeInformation = Field(
        ...,
        description='Information required for data set management and administration.',
    )
    characterisationFactors: CharacterisationFactors = Field(
        ...,
        description='Flow / Exchanges list with corresponding impact factors according to the respective LCIA method.',
    )
    common_other: str | None = Field(None, alias='common:other')


class Model(BaseModel):
    LCIAMethodDataSet_1: LCIAMethodDataSet = Field(..., alias='LCIAMethodDataSet')
