# generated by datamodel-codegen:
#   filename:  tidas_flowproperties.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class CommonApprovalOfOverallCompliance(Enum):
    """
    Official approval whether or not and in how far the data set meets all the requirements of the "Compliance system" refered to. This approval should be issued/confirmed by the owner of that compliance system, who is identified via the respective "Contact data set".
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CASNumber(RootModel[str]):
    root: str = Field(
        ...,
        description='CAS Number, leading zeros are requried.',
        pattern='^[0-9]{2,7}-[0-9]{2}-[0-9]$',
    )


class FT(RootModel[str]):
    root: str = Field(..., description='Free text with an unlimited length.')


class StringMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=500)


class StringMultiLang1(RootModel[list[StringMultiLang1Item]]):
    root: list[StringMultiLang1Item] = Field(
        ..., description='Multi-language string with a maximum length of 500 characters'
    )


class StringMultiLang2(BaseModel):
    """
    Multi-language string with a maximum length of 500 characters
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=500)


class Int5(RootModel[str]):
    root: str = Field(
        ..., description='5-digit integer number', pattern='^(0|[1-9]\\d{0,4})$'
    )


class Int6(RootModel[str]):
    root: str = Field(
        ..., description='6-digit integer number', pattern='^(0|[1-9]\\d{0,5})$'
    )


class Perc(RootModel[str]):
    root: str = Field(
        ...,
        description='percentage amount',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )


class MatR(RootModel[str]):
    root: str = Field(..., description='Mathematical rule')


class MatV(RootModel[str]):
    root: str = Field(..., description='Mathematical variable or parameter')


class Real(RootModel[str]):
    root: str = Field(
        ...,
        description='38-digit real number',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )


class ST(RootModel[str]):
    root: str = Field(
        ...,
        description='Short text with a maximum length of 1000 characters',
        max_length=1000,
    )


class String(RootModel[str]):
    root: str = Field(
        ...,
        description='String with a maximum length of 500 characters. Must have a minimum length of 1.',
        max_length=500,
        min_length=1,
    )


class STMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=1000)


class STMultiLang1(RootModel[list[STMultiLang1Item]]):
    root: list[STMultiLang1Item] = Field(
        ...,
        description='Multi-lang short text with a maximum length of 1000 characters.',
    )


class STMultiLang2(BaseModel):
    """
    Multi-lang short text with a maximum length of 1000 characters.
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=1000)


class FTMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text')


class FTMultiLang1(RootModel[list[FTMultiLang1Item]]):
    root: list[FTMultiLang1Item] = Field(
        ..., description='Multi-lang free text with an unlimited length.'
    )


class FTMultiLang2(BaseModel):
    """
    Multi-lang free text with an unlimited length.
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text')


class GlobalReferenceType1(BaseModel):
    """
    Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.
    """

    field_type: str = Field(..., alias='@type')
    field_refObjectId: str = Field(
        ...,
        alias='@refObjectId',
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )
    field_version: str = Field(..., alias='@version')
    field_uri: str = Field(..., alias='@uri')
    common_shortDescription: STMultiLang1 | STMultiLang2 = Field(
        ...,
        alias='common:shortDescription',
        description='Multi-lang short text with a maximum length of 1000 characters.'
    )


class GlobalReferenceTypeItem(BaseModel):
    field_type: str = Field(..., alias='@type')
    field_refObjectId: str = Field(
        ...,
        alias='@refObjectId',
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )
    field_version: str = Field(..., alias='@version')
    field_uri: str = Field(..., alias='@uri')
    common_shortDescription: STMultiLang1 | STMultiLang2 = Field(
        ...,
        alias='common:shortDescription',
        description='Multi-lang short text with a maximum length of 1000 characters.'
    )


class GIS(RootModel[str]):
    root: str = Field(
        ...,
        description='Global geographical reference in Latitude and LongitudeExamples: "+42.42;-180", "0;0", "13.22 ; -3"',
        pattern='^\\s*[+-]?((90(\\.0+)?)|([0-8]?\\d(\\.\\d+)?))\\s*;\\s*[+-]?((180(\\.0+)?)|((1[0-7]\\d|[0-9]?\\d)(\\.\\d+)?))\\s*$',
    )


class Year(RootModel[int]):
    root: int = Field(..., description='4-digit year', ge=1000, le=9999)


class DateTime(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(
        ..., description='Date and time format acc. to ISO 8601'
    )


class CommonClass(BaseModel):
    field_level: str = Field(
        ...,
        alias='@level',
        description='1-digit integer number, must be equal to or greater than 0',
        pattern='^[0-9]$',
    )
    field_classId: str = Field(..., alias='@classId')
    text: str = Field(..., alias='#text')


class CommonClassification(BaseModel):
    """
    Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.
    """

    common_class: CommonClass = Field(..., alias='common:class')
    common_other: str | None = Field(None, alias='common:other')


class ClassificationInformation(BaseModel):
    """
    Hierachical classification of the Flow property foreseen to be used to structure the Flow property content of the database. (Note: This entry is NOT required for the identification of the Flow property data set. It should nevertheless be avoided to use identical names for Flow properties in the same class.
    """

    common_classification: CommonClassification = Field(
        ...,
        alias='common:classification',
        description='Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.',
    )


class DataSetInformation(BaseModel):
    common_UUID: str = Field(
        ...,
        alias='common:UUID',
        description='Automatically generated Universally Unique Identifier of this data set. Together with the "Data set version", the UUID uniquely identifies each data set.',
        pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    )
    common_name: StringMultiLang1 | StringMultiLang2 = Field(
        ...,
        alias='common:name',
        description='Name of flow property.'
    )
    common_synonyms: FTMultiLang1 | FTMultiLang2 | None = Field(
        None,
        alias='common:synonyms',
        description='Synonyms are alternative names for the "Name" of the Flow property.'
    )
    classificationInformation: ClassificationInformation = Field(
        ...,
        description='Hierachical classification of the Flow property foreseen to be used to structure the Flow property content of the database. (Note: This entry is NOT required for the identification of the Flow property data set. It should nevertheless be avoided to use identical names for Flow properties in the same class.',
    )
    common_generalComment: FTMultiLang1 | FTMultiLang2 | None = Field(
        None,
        alias='common:generalComment',
        description='Free text for general information about the data set. It may contain comments on e.g. information sources used as well as general (internal, not reviewed) quality statements.'
    )
    common_other: str | None = Field(None, alias='common:other')


class QuantitativeReference(BaseModel):
    """
    This section allows to refer to the Flow property's quantitative reference, which is always a unit (i.e. that unit, in which the property is measured, e.g. "MJ" for energy-related Flow properties).
    """

    referenceToReferenceUnitGroup: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        description='"Unit group data set" and its reference unit, in which the Flow property is measured.'
    )
    common_other: str | None = Field(None, alias='common:other')


class FlowPropertiesInformation(BaseModel):
    dataSetInformation: DataSetInformation
    quantitativeReference: QuantitativeReference = Field(
        ...,
        description='This section allows to refer to the Flow property\'s quantitative reference, which is always a unit (i.e. that unit, in which the property is measured, e.g. "MJ" for energy-related Flow properties).',
    )
    common_other: str | None = Field(None, alias='common:other')


class DataSourcesTreatmentAndRepresentativeness(BaseModel):
    referenceToDataSource: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='"Source data set" of data source(s) used for the data set e.g. a paper, a questionnaire, a monography etc. The main raw data sources should be named, too. [Note: relevant especially for market price data.]'
    )
    common_other: str | None = Field(None, alias='common:other')


class Compliance(BaseModel):
    """
    One compliance declaration. Multiple declarations may be provided.
    """

    common_referenceToComplianceSystem: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToComplianceSystem',
        description='"Source data set" of the "Compliance system" that is declared to be met by the data set.'
    )
    common_approvalOfOverallCompliance: CommonApprovalOfOverallCompliance = Field(
        ...,
        alias='common:approvalOfOverallCompliance',
        description='Official approval whether or not and in how far the data set meets all the requirements of the "Compliance system" refered to. This approval should be issued/confirmed by the owner of that compliance system, who is identified via the respective "Contact data set".',
    )


class Compliance1Item(BaseModel):
    common_referenceToComplianceSystem: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToComplianceSystem',
        description='"Source data set" of the "Compliance system" that is declared to be met by the data set.'
    )
    common_approvalOfOverallCompliance: CommonApprovalOfOverallCompliance = Field(
        ...,
        alias='common:approvalOfOverallCompliance',
        description='Official approval whether or not and in how far the data set meets all the requirements of the "Compliance system" refered to. This approval should be issued/confirmed by the owner of that compliance system, who is identified via the respective "Contact data set".',
    )


class Compliance1(RootModel[list[Compliance1Item]]):
    root: list[Compliance1Item] = Field(
        ...,
        description='One compliance declaration. Multiple declarations may be provided.',
        min_length=1,
    )


class ComplianceDeclarations(BaseModel):
    """
    Statements on compliance of several data set aspects with compliance requirements as defined by the referenced compliance system (e.g. an EPD scheme, handbook of a national or international data network such as the ILCD, etc.).
    """

    compliance: Compliance | Compliance1 = Field(
        ...,
        description='One compliance declaration. Multiple declarations may be provided.'
    )
    common_other: str | None = Field(None, alias='common:other')


class ModellingAndValidation(BaseModel):
    """
    Covers the five sub-sections 1) LCI method (not used), 2) Data sources, treatment and representativeness (only 3 fields), 3) Completeness (not used), 4) Validation, and 5) Compliance.
    """

    dataSourcesTreatmentAndRepresentativeness: (
        DataSourcesTreatmentAndRepresentativeness | None
    ) = None
    complianceDeclarations: ComplianceDeclarations = Field(
        ...,
        description='Statements on compliance of several data set aspects with compliance requirements as defined by the referenced compliance system (e.g. an EPD scheme, handbook of a national or international data network such as the ILCD, etc.).',
    )
    common_other: str | None = Field(None, alias='common:other')


class DataEntryBy(BaseModel):
    """
    Staff or entity, that documented the generated data set, entering the information into the database; plus administrative information linked to the data entry activity.
    """

    common_timeStamp: AwareDatetime = Field(
        ...,
        alias='common:timeStamp',
        description='Date and time stamp of data set generation, typically an automated entry ("last saved").',
    )
    common_referenceToDataSetFormat: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToDataSetFormat',
        description='"Source data set" of the used version of the ILCD format. If additional data format fields have been integrated into the data set file, using the "namespace" option, the used format namespace(s) are to be given. This is the case if the data sets carries additional information as specified by other, particular LCA formats, e.g. of other database networks or LCA softwares.'
    )
    common_other: str | None = Field(None, alias='common:other')


class PublicationAndOwnership(BaseModel):
    """
    Information related to publication and version management of the data set including copyright and access restrictions.
    """

    common_dataSetVersion: str = Field(
        ...,
        alias='common:dataSetVersion',
        description='Version number of data set. First two digits refer to major updates, the second two digits to minor revisions and error corrections etc. The third three digits are intended for automatic and internal counting of versions during data set development. Together with the data set\'s UUID, the "Data set version" uniquely identifies each data set.',
    )
    common_referenceToPrecedingDataSetVersion: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        alias='common:referenceToPrecedingDataSetVersion',
        description='Last preceding data set, which was replaced by this version. Either a URI of that data set (i.e. an internet address) or its UUID plus version number is given (or both).'
    )
    common_permanentDataSetURI: AnyUrl | None = Field(
        None,
        alias='common:permanentDataSetURI',
        description="URI (i.e. an internet address) of the original of this data set. [Note: This equally globally unique identifier supports users and software tools to identify and retrieve the original version of a data set via the internet or to check for available updates. The URI must not represent an existing WWW address, but it should be unique and point to the data access point, e.g. by combining the data owner's www path with the data set's UUID, e.g. http://www.mycompany.com/lca/processes/50f12420-8855-12db-b606-0900210c9a66.]",
    )
    common_referenceToOwnershipOfDataSet: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToOwnershipOfDataSet',
        description='"Contact data set" of the person or entity who owns this data set. (Note: this is not necessarily the publisher of the data set.)'
    )
    common_other: str | None = Field(None, alias='common:other')


class AdministrativeInformation(BaseModel):
    """
    Information on data set management and administration.
    """

    dataEntryBy: DataEntryBy = Field(
        ...,
        description='Staff or entity, that documented the generated data set, entering the information into the database; plus administrative information linked to the data entry activity.',
    )
    publicationAndOwnership: PublicationAndOwnership = Field(
        ...,
        description='Information related to publication and version management of the data set including copyright and access restrictions.',
    )
    common_other: str | None = Field(None, alias='common:other')


class FlowPropertyDataSet(BaseModel):
    field_xmlns: Literal['http://lca.jrc.it/ILCD/FlowProperty'] = Field(
        ..., alias='@xmlns'
    )
    field_xmlns_common: Literal['http://lca.jrc.it/ILCD/Common'] = Field(
        ..., alias='@xmlns:common'
    )
    field_xmlns_xsi: Literal['http://www.w3.org/2001/XMLSchema-instance'] = Field(
        ..., alias='@xmlns:xsi'
    )
    field_version: Literal['1.1'] = Field(..., alias='@version')
    field_xsi_schemaLocation: Literal[
        'http://lca.jrc.it/ILCD/FlowProperty ../../schemas/ILCD_FlowPropertyDataSet.xsd'
    ] = Field(..., alias='@xsi:schemaLocation')
    flowPropertiesInformation: FlowPropertiesInformation
    modellingAndValidation: ModellingAndValidation | None = Field(
        None,
        description='Covers the five sub-sections 1) LCI method (not used), 2) Data sources, treatment and representativeness (only 3 fields), 3) Completeness (not used), 4) Validation, and 5) Compliance.',
    )
    administrativeInformation: AdministrativeInformation = Field(
        ..., description='Information on data set management and administration.'
    )
    common_other: str | None = Field(None, alias='common:other')


class Model(BaseModel):
    flowPropertyDataSet: FlowPropertyDataSet
