# generated by datamodel-codegen:
#   filename:  tidas_flows.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class CommonCategoryItem(BaseModel):
    field_level: Literal['0'] = Field(..., alias='@level')
    field_catId: str = Field(..., alias='@catId')
    text: str = Field(..., alias='#text')


class CommonCategoryItem1(BaseModel):
    field_level: Literal['1'] = Field(..., alias='@level')
    field_catId: str = Field(..., alias='@catId')
    text: str = Field(..., alias='#text')


class CommonCategoryItem2(BaseModel):
    field_level: Literal['2'] = Field(..., alias='@level')
    field_catId: str = Field(..., alias='@catId')
    text: str = Field(..., alias='#text')


class CommonCategory(BaseModel):
    pass


class CommonElementaryFlowCategorization(BaseModel):
    common_category: (
        list[CommonCategoryItem | CommonCategoryItem1 | CommonCategoryItem2]
        | CommonCategory
    ) = Field(..., alias='common:category')
    common_other: str | None = Field(None, alias='common:other')


class CommonClas(BaseModel):
    field_level: Literal['0'] = Field(..., alias='@level')
    field_classId: str = Field(..., alias='@classId')
    text: str = Field(..., alias='#text')


class CommonClas1(BaseModel):
    field_level: Literal['1'] = Field(..., alias='@level')
    field_classId: str = Field(..., alias='@classId')
    text: str = Field(..., alias='#text')


class CommonClas2(BaseModel):
    field_level: Literal['2'] = Field(..., alias='@level')
    field_classId: str = Field(..., alias='@classId')
    text: str = Field(..., alias='#text')


class CommonClas3(BaseModel):
    field_level: Literal['3'] = Field(..., alias='@level')
    field_classId: str = Field(..., alias='@classId')
    text: str = Field(..., alias='#text')


class CommonClas4(BaseModel):
    field_level: Literal['4'] = Field(..., alias='@level')
    field_classId: str = Field(..., alias='@classId')
    text: str = Field(..., alias='#text')


CommonClass = CommonCategory


class CommonClassification(BaseModel):
    common_class: (
        list[CommonClas | CommonClas1 | CommonClas2 | CommonClas3 | CommonClas4]
        | CommonClass
    ) = Field(..., alias='common:class')
    common_other: str | None = Field(None, alias='common:other')


class ClassificationInformation(BaseModel):
    """
    Hierachical classification of the Flow property foreseen to be used to structure the Flow property content of the database. (Note: This entry is NOT required for the identification of the Flow property data set. It should nevertheless be avoided to use identical names for Flow properties in the same class.
    """

    common_elementaryFlowCategorization: CommonElementaryFlowCategorization = Field(
        ..., alias='common:elementaryFlowCategorization'
    )
    common_classification: CommonClassification | None = Field(
        None, alias='common:classification'
    )


CommonCategoryItem3 = CommonCategoryItem


CommonCategoryItem4 = CommonCategoryItem1


CommonCategoryItem5 = CommonCategoryItem2


class CommonElementaryFlowCategorization1(BaseModel):
    common_category: (
        list[CommonCategoryItem3 | CommonCategoryItem4 | CommonCategoryItem5]
        | CommonCategory
    ) = Field(..., alias='common:category')
    common_other: str | None = Field(None, alias='common:other')


CommonClas5 = CommonClas


CommonClas6 = CommonClas1


CommonClas7 = CommonClas2


CommonClas8 = CommonClas3


CommonClas9 = CommonClas4


class CommonClassification1(BaseModel):
    common_class: (
        list[CommonClas5 | CommonClas6 | CommonClas7 | CommonClas8 | CommonClas9]
        | CommonClass
    ) = Field(..., alias='common:class')
    common_other: str | None = Field(None, alias='common:other')


class ClassificationInformation1(BaseModel):
    """
    Hierachical classification of the Flow property foreseen to be used to structure the Flow property content of the database. (Note: This entry is NOT required for the identification of the Flow property data set. It should nevertheless be avoided to use identical names for Flow properties in the same class.
    """

    common_elementaryFlowCategorization: CommonElementaryFlowCategorization1 | None = (
        Field(None, alias='common:elementaryFlowCategorization')
    )
    common_classification: CommonClassification1 = Field(
        ..., alias='common:classification'
    )


class TypeOfDataSet(Enum):
    Elementary_flow = 'Elementary flow'
    Product_flow = 'Product flow'
    Waste_flow = 'Waste flow'


class LCIMethod(BaseModel):
    typeOfDataSet: TypeOfDataSet
    common_other: str | None = Field(None, alias='common:other')


class CommonApprovalOfOverallCompliance(Enum):
    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class UncertaintyDistributionType(Enum):
    undefined = 'undefined'
    log_normal = 'log-normal'
    normal = 'normal'
    triangular = 'triangular'
    uniform = 'uniform'


class DataDerivationTypeStatus(Enum):
    Measured = 'Measured'
    Calculated = 'Calculated'
    Estimated = 'Estimated'
    Unknown_derivation = 'Unknown derivation'


class FT(RootModel[str]):
    root: str = Field(..., description='Free text with an unlimited length.')


class StringMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=500)


class StringMultiLang1(RootModel[list[StringMultiLang1Item]]):
    root: list[StringMultiLang1Item] = Field(
        ..., description='Multi-language string with a maximum length of 500 characters'
    )


class StringMultiLang2(BaseModel):
    """
    Multi-language string with a maximum length of 500 characters
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=500)


class StringMultiLang(RootModel[StringMultiLang1 | StringMultiLang2]):
    root: StringMultiLang1 | StringMultiLang2 = Field(
        ...,
        description='Multi-language string with a maximum length of 500 characters'
    )


class Int5(RootModel[str]):
    root: str = Field(
        ..., description='5-digit integer number', pattern='^(0|[1-9]\\d{0,4})$'
    )


class Int6(RootModel[str]):
    root: str = Field(
        ..., description='6-digit integer number', pattern='^(0|[1-9]\\d{0,5})$'
    )


class LevelType(RootModel[str]):
    root: str = Field(
        ...,
        description='1-digit integer number, must be equal to or greater than 0',
        pattern='^[0-9]$',
    )


class Perc(RootModel[str]):
    root: str = Field(
        ...,
        description='percentage amount',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )


class MatR(RootModel[str]):
    root: str = Field(..., description='Mathematical rule')


class MatV(RootModel[str]):
    root: str = Field(..., description='Mathematical variable or parameter')


class Real(RootModel[str]):
    root: str = Field(
        ...,
        description='38-digit real number',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )


class ST(RootModel[str]):
    root: str = Field(
        ...,
        description='Short text with a maximum length of 1000 characters',
        max_length=1000,
    )


class STMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=1000)


class STMultiLang1(RootModel[list[STMultiLang1Item]]):
    root: list[STMultiLang1Item] = Field(
        ...,
        description='Multi-lang short text with a maximum length of 1000 characters.',
    )


class STMultiLang2(BaseModel):
    """
    Multi-lang short text with a maximum length of 1000 characters.
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=1000)


class FTMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text')


class FTMultiLang1(RootModel[list[FTMultiLang1Item]]):
    root: list[FTMultiLang1Item] = Field(
        ..., description='Multi-lang free text with an unlimited length.'
    )


class FTMultiLang2(BaseModel):
    """
    Multi-lang free text with an unlimited length.
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text')


class GlobalReferenceType1(BaseModel):
    """
    Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.
    """

    field_type: str = Field(..., alias='@type')
    field_refObjectId: str = Field(
        ...,
        alias='@refObjectId',
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )
    field_version: str = Field(..., alias='@version')
    field_uri: str = Field(..., alias='@uri')
    common_shortDescription: STMultiLang1 | STMultiLang2 = Field(
        ...,
        alias='common:shortDescription',
        description='Multi-lang short text with a maximum length of 1000 characters.'
    )


class GlobalReferenceTypeItem(BaseModel):
    field_type: str = Field(..., alias='@type')
    field_refObjectId: str = Field(
        ...,
        alias='@refObjectId',
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )
    field_version: str = Field(..., alias='@version')
    field_uri: str = Field(..., alias='@uri')
    common_shortDescription: STMultiLang1 | STMultiLang2 = Field(
        ...,
        alias='common:shortDescription',
        description='Multi-lang short text with a maximum length of 1000 characters.'
    )


class GlobalReferenceType(
    RootModel[GlobalReferenceType1 | list[GlobalReferenceTypeItem]]
):
    root: GlobalReferenceType1 | list[GlobalReferenceTypeItem] = Field(
        ...,
        description='Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.'
    )


class GIS(RootModel[str]):
    root: str = Field(
        ...,
        description='Global geographical reference in Latitude and LongitudeExamples: "+42.42;-180", "0;0", "13.22 ; -3"',
        pattern='^\\s*[+-]?((90(\\.0+)?)|([0-8]?\\d(\\.\\d+)?))\\s*;\\s*[+-]?((180(\\.0+)?)|((1[0-7]\\d|[0-9]?\\d)(\\.\\d+)?))\\s*$',
    )


class Year(RootModel[int]):
    root: int = Field(..., description='4-digit year', ge=1000, le=9999)


class Name(BaseModel):
    baseName: StringMultiLang1 | StringMultiLang2 = Field(
        ...,
        description='Multi-language string with a maximum length of 500 characters'
    )
    treatmentStandardsRoutes: StringMultiLang1 | StringMultiLang2 = Field(
        ...,
        description='Multi-language string with a maximum length of 500 characters'
    )
    mixAndLocationTypes: StringMultiLang1 | StringMultiLang2 = Field(
        ...,
        description='Multi-language string with a maximum length of 500 characters'
    )
    flowProperties: StringMultiLang1 | StringMultiLang2 | None = Field(
        None,
        description='Multi-language string with a maximum length of 500 characters'
    )
    common_other: str | None = Field(None, alias='common:other')


class DataSetInformation(BaseModel):
    common_UUID: str = Field(
        ...,
        alias='common:UUID',
        description='Automatically generated Universally Unique Identifier of this data set. Together with the "Data set version", the UUID uniquely identifies each data set.',
        pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    )
    name: Name
    common_synonyms: FTMultiLang1 | FTMultiLang2 | None = Field(
        None,
        alias='common:synonyms',
        description='Synonyms / alternative names / brands of the good, service, or process. Separated by semicolon.'
    )
    classificationInformation: (
        ClassificationInformation | ClassificationInformation1
    ) = Field(
        ...,
        description='Hierachical classification of the Flow property foreseen to be used to structure the Flow property content of the database. (Note: This entry is NOT required for the identification of the Flow property data set. It should nevertheless be avoided to use identical names for Flow properties in the same class.'
    )
    CASNumber: str | None = Field(
        None,
        description='Chemical Abstract Systems Number of the substance. [Note: Should only be given for (virtually) pure substances, but NOT also for the main constituent of a material or product etc.]',
        pattern='^[0-9]{2,7}-[0-9]{2}-[0-9]$',
    )
    sumFormula: str | None = Field(
        None,
        description='Chemical sum formula of the substance.',
        max_length=500,
        min_length=1,
    )
    common_generalComment: FTMultiLang1 | FTMultiLang2 | None = Field(
        None,
        alias='common:generalComment',
        description='Free text for general information about the Flow data set. It may contain information about e.g. the use of the substance, good, service or process in a specific technology or industry-context, information sources used, data selection principles etc.'
    )
    common_other: str | None = Field(None, alias='common:other')


class QuantitativeReference(BaseModel):
    referenceToReferenceFlowProperty: str = Field(
        ..., description='5-digit integer number', pattern='^(0|[1-9]\\d{0,4})$'
    )
    common_other: str | None = Field(None, alias='common:other')


class Geography(BaseModel):
    locationOfSupply: str | None = Field(None)
    common_other: str | None = Field(None, alias='common:other')


class Technology(BaseModel):
    technologicalApplicability: FTMultiLang1 | FTMultiLang2 | None = Field(
        None,
        description='Description of the intended / possible applications of the good or service, or waste. E.g. for which type of products the material, represented by this data set, is used. Examples: "This high purity chemical is used for analytical laboratories only." or "This technical quality bulk chemical is used for large scale synthesis in chemical industry.". Or: "This type of biowaste is typically composted or biodigested as the water content is too high for efficient combustion".'
    )
    referenceToTechnicalSpecification: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        description='"Source data set(s)" of the product\'s or waste\'s technical specification, waste data sheet, safety data sheet, etc.'
    )
    common_other: str | None = Field(None, alias='common:other')


class FlowInformation(BaseModel):
    dataSetInformation: DataSetInformation
    quantitativeReference: QuantitativeReference
    geography: Geography | None = None
    technology: Technology | None = None
    common_other: str | None = Field(None, alias='common:other')


class Compliance(BaseModel):
    """
    One compliance declaration. Multiple declarations may be provided.
    """

    common_referenceToComplianceSystem: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToComplianceSystem',
        description='Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.'
    )
    common_approvalOfOverallCompliance: CommonApprovalOfOverallCompliance = Field(
        ..., alias='common:approvalOfOverallCompliance'
    )
    common_other: str | None = Field(None, alias='common:other')


class Compliance1Item(BaseModel):
    common_referenceToComplianceSystem: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToComplianceSystem',
        description='Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.'
    )
    common_approvalOfOverallCompliance: CommonApprovalOfOverallCompliance = Field(
        ..., alias='common:approvalOfOverallCompliance'
    )
    common_other: str | None = Field(None, alias='common:other')


class Compliance1(RootModel[list[Compliance1Item]]):
    root: list[Compliance1Item] = Field(
        ...,
        description='One compliance declaration. Multiple declarations may be provided.',
        min_length=1,
    )


class ComplianceDeclarations(BaseModel):
    compliance: Compliance | Compliance1 = Field(
        ...,
        description='One compliance declaration. Multiple declarations may be provided.'
    )
    common_other: str | None = Field(None, alias='common:other')


class ModellingAndValidation(BaseModel):
    LCIMethod_1: LCIMethod = Field(..., alias='LCIMethod')
    complianceDeclarations: ComplianceDeclarations
    common_other: str | None = Field(None, alias='common:other')


class DataEntryBy(BaseModel):
    common_timeStamp: AwareDatetime = Field(
        ...,
        alias='common:timeStamp',
        description='Date and time stamp of data set generation, typically an automated entry ("last saved").',
    )
    common_referenceToDataSetFormat: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToDataSetFormat',
        description='"Source data set" of the used version of the ILCD format. If additional data format fields have been integrated into the data set file, using the "namespace" option, the used format namespace(s) are to be given. This is the case if the data sets carries additional information as specified by other, particular LCA formats, e.g. of other database networks or LCA softwares.'
    )
    common_referenceToPersonOrEntityEnteringTheData: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        alias='common:referenceToPersonOrEntityEnteringTheData',
        description='"Contact data set" of the responsible person or entity that has documented this data set, i.e. entered the data and the descriptive information.'
    )
    common_other: str | None = Field(None, alias='common:other')


class PublicationAndOwnership(BaseModel):
    common_dataSetVersion: str = Field(
        ...,
        alias='common:dataSetVersion',
        description='Version number of data set. First two digits refer to major updates, the second two digits to minor revisions and error corrections etc. The third three digits are intended for automatic and internal counting of versions during data set development. Together with the data set\'s UUID, the "Data set version" uniquely identifies each data set.',
    )
    common_referenceToPrecedingDataSetVersion: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        alias='common:referenceToPrecedingDataSetVersion',
        description='Last preceding data set, which was replaced by this version. Either a URI of that data set (i.e. an internet address) or its UUID plus version number is given (or both).'
    )
    common_permanentDataSetURI: AnyUrl | None = Field(
        None,
        alias='common:permanentDataSetURI',
        description="URI (i.e. an internet address) of the original of this data set. [Note: This equally globally unique identifier supports users and software tools to identify and retrieve the original version of a data set via the internet or to check for available updates. The URI must not represent an existing WWW address, but it should be unique and point to the data access point, e.g. by combining the data owner's www path with the data set's UUID, e.g. http://www.mycompany.com/lca/processes/50f12420-8855-12db-b606-0900210c9a66.]",
    )
    common_referenceToOwnershipOfDataSet: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToOwnershipOfDataSet',
        description='"Contact data set" of the person or entity who owns this data set. (Note: this is not necessarily the publisher of the data set.)'
    )
    common_other: str | None = Field(None, alias='common:other')


class AdministrativeInformation(BaseModel):
    dataEntryBy: DataEntryBy
    publicationAndOwnership: PublicationAndOwnership
    common_other: str | None = Field(None, alias='common:other')


class FlowProperty(BaseModel):
    field_dataSetInternalID: str = Field(
        ...,
        alias='@dataSetInternalID',
        description='Automated entry: internal ID, used in the "Quantitative reference" section to identify the reference flow property.',
        pattern='^(0|[1-9]\\d{0,4})$',
    )
    referenceToFlowPropertyDataSet: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        description='Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.'
    )
    meanValue: str = Field(
        ...,
        description='Value for the flow expressed in this flow property in relationship to the the value of the flow expressed in its reference flow property (see field "Reference to reference flow property" in the "Quantitative reference" section). [Notes and examples: If the product flow "Diesel" is expressed by default in "Mass" (= reference flow property) and "kg" (= corresponding reference unit), the value that would be stated here for an additional flow property e.g. "Net calorific value" would be "42.5", as this flow property has the reference unit "MJ" and Diesel has a net calorific value of 42.5 MJ per 1 kg. It is recommended to report only significant digits of the value.]',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    minimumValue: str | None = Field(
        None,
        description='Minimum value of this flow property in case uncertainty distribution is uniform or triangular.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    maximumValue: str | None = Field(
        None,
        description='Maximum value of this flow property in case uncertainty distribution is uniform or triangular.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    uncertaintyDistributionType: UncertaintyDistributionType | None = None
    relativeStandardDeviation95In: str | None = Field(
        None,
        description='The resulting overall uncertainty of the calculated variable value considering uncertainty of measurements, modelling, appropriateness etc. [Notes: For log-normal distribution the square of the geometric standard deviation (SDg^2) is stated. Mean value times SDg^2 equals the 97.5% value (= Maximum value), Mean value divided by SDg^2 equals the 2.5% value (= Minimum value). For normal distribution the doubled standard deviation value (2*SD) is entered. Mean value plus 2*SD equals 97.5% value (= Maximum value), Mean value minus 2*SD equals 2.5% value (= Minimum value). This data field remains empty when uniform or triangular uncertainty distribution is applied.]',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )
    dataDerivationTypeStatus: DataDerivationTypeStatus | None = None
    generalComment: StringMultiLang1 | StringMultiLang2 | None = Field(
        None,
        description='Multi-language string with a maximum length of 500 characters'
    )
    common_other: str | None = Field(None, alias='common:other')


FlowPropertyItem = FlowProperty


class FlowProperties(BaseModel):
    flowProperty: FlowProperty | list[FlowPropertyItem] = Field(...)
    common_other: str | None = Field(None, alias='common:other')


class FlowDataSet(BaseModel):
    field_xmlns: Literal['http://lca.jrc.it/ILCD/Flow'] = Field(..., alias='@xmlns')
    field_xmlns_common: Literal['http://lca.jrc.it/ILCD/Common'] = Field(
        ..., alias='@xmlns:common'
    )
    field_xmlns_ecn: Literal[
        'http://eplca.jrc.ec.europa.eu/ILCD/Extensions/2018/ECNumber'
    ] = Field(..., alias='@xmlns:ecn')
    field_xmlns_xsi: Literal['http://www.w3.org/2001/XMLSchema-instance'] = Field(
        ..., alias='@xmlns:xsi'
    )
    field_version: Literal['1.1'] = Field(..., alias='@version')
    field_locations: Literal['../ILCDLocations.xml'] = Field(..., alias='@locations')
    field_xsi_schemaLocation: Literal[
        'http://lca.jrc.it/ILCD/Flow ../../schemas/ILCD_FlowDataSet.xsd'
    ] = Field(..., alias='@xsi:schemaLocation')
    flowInformation: FlowInformation
    modellingAndValidation: ModellingAndValidation
    administrativeInformation: AdministrativeInformation
    flowProperties: FlowProperties
    common_other: str | None = Field(None, alias='common:other')


class Model(BaseModel):
    flowDataSet: FlowDataSet
