# generated by datamodel-codegen:
#   filename:  tidas_contacts.json

from __future__ import annotations

from typing import Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from tidas_sdk.types.tidas_contacts_category import (
    Contacts,
    TidasContactsText
)

from tidas_sdk.types.tidas_data_types import (
    CASNumber,
    FT,
    FTMultiLang,
    GIS,
    GlobalReferenceType,
    GlobalReferenceTypeOrArray,
    Int1,
    Int5,
    Int6,
    LevelType,
    MatR,
    MatV,
    MultiLangItem,
    MultiLangItemST,
    MultiLangItemString,
    Perc,
    Real,
    ST,
    STMultiLang,
    String,
    StringMultiLang,
    UUID,
    Year
)



class CommonClas(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    field_level: Literal['0'] = Field(..., alias='@level')
    field_classId: Contacts = Field(..., alias='@classId')
    text: TidasContactsText = Field(..., alias='#text')


class CommonClas1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    field_level: Literal['1'] = Field(..., alias='@level')
    field_classId: Contacts = Field(..., alias='@classId')
    text: TidasContactsText = Field(..., alias='#text')


class CommonClass1(BaseModel):
    pass
    model_config = ConfigDict(
        extra='allow',
    )


class CommonClass(RootModel[list[CommonClas | CommonClas1] | CommonClass1]):
    root: list[CommonClas | CommonClas1] | CommonClass1 = Field(..., union_mode='smart')


CommonClass2 = CommonClas


class CommonClassification(BaseModel):
    """
    Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    common_class: CommonClass | CommonClass2 = Field(
        ..., alias='common:class'
    )


class ClassificationInformation(BaseModel):
    """
    Hierachical classification of the contact foreseen to be used to structure the contact content of the database. (Note: This entry is NOT required for the identification of the contact data set. It should nevertheless be avoided to use identical names for contacts in the same class.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    common_classification: CommonClassification = Field(
        ...,
        alias='common:classification',
        description='Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.',
    )
    common_other: str | None = Field(None, alias='common:other')


class DataSetInformation(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    common_UUID: str = Field(
        ...,
        alias='common:UUID',
        description="Automatically generated Universally Unique Identifier of this data set. Together with the 'Data set version', the UUID uniquely identifies each data set.",
        pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    )
    common_shortName: StringMultiLang = Field(
        ...,
        alias='common:shortName',
        description="Short name for the contact, that is used for display e.g. of links to this data set (especially in case the full name of the contact is rather long, e.g. 'FAO' for 'Food and Agriculture Organization').",
        union_mode='smart',
    )
    common_name: StringMultiLang = Field(
        ...,
        alias='common:name',
        description='Name of the person, working group, organisation, or database network, which is represented by this contact data set.',
        union_mode='smart',
    )
    classificationInformation: ClassificationInformation = Field(
        ...,
        description='Hierachical classification of the contact foreseen to be used to structure the contact content of the database. (Note: This entry is NOT required for the identification of the contact data set. It should nevertheless be avoided to use identical names for contacts in the same class.',
    )
    contactAddress: STMultiLang | None = Field(
        None,
        description="Mail address of the contact; specific for the person, working group, or department. [Note: A general contact point to the organisation is to be given in 'General contact point'.]",
        union_mode='smart',
    )
    email: str | None = Field(
        None,
        description='String with a maximum length of 500 characters. Must have a minimum length of 1.',
        max_length=500,
        min_length=1,
    )
    telephone: str | None = Field(
        None,
        description='String with a maximum length of 500 characters. Must have a minimum length of 1.',
        max_length=500,
        min_length=1,
    )
    telefax: str | None = Field(
        None,
        description='String with a maximum length of 500 characters. Must have a minimum length of 1.',
        max_length=500,
        min_length=1,
    )
    WWWAddress: str | None = Field(
        None,
        description='Web-address of the person, working group, organisation or database network.',
        max_length=1000,
    )
    centralContactPoint: STMultiLang | None = Field(
        None,
        description='Alternative address / contact details for the contact. Provides contact information in case e.g. the person or group represented by this contact has left the organisation or changed office/telephone. This alternative contact point can hence contain also a central telephone number, e-mail, www-address etc. of the organisation.',
        union_mode='smart',
    )
    contactDescriptionOrComment: STMultiLang | None = Field(
        None,
        description='Free text for additional description of the organisation or person of the contact, such as organisational profile, person responsibilities, etc.',
        union_mode='smart',
    )
    referenceToContact: GlobalReferenceType | list[GlobalReferenceType] | None = (
        Field(
            None,
            description='"Contact data set"s of working groups, organisations or database networks to which EITHER this person or entity OR this database, data set format, or compliance system belongs. [Note: This does not necessarily imply a legally binding relationship, but may also be a voluntary membership.]',
            union_mode='smart',
        )
    )
    referenceToLogo: GlobalReferenceType | list[GlobalReferenceType] | None = (
        Field(
            None,
            description='"Source data set" of the logo of the organisation or source to be used in reports etc.',
            union_mode='smart',
        )
    )
    common_other: str | None = Field(None, alias='common:other')


class ContactInformation(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    dataSetInformation: DataSetInformation
    common_other: str | None = Field(None, alias='common:other')


class DataEntryBy(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    common_timeStamp: AwareDatetime = Field(
        ...,
        alias='common:timeStamp',
        description="Date and time stamp of data set generation, typically an automated entry ('last saved').",
    )
    common_referenceToDataSetFormat: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToDataSetFormat',
        description='"Source data set" of the used version of the ILCD format. If additional data format fields have been integrated into the data set file, using the "namespace" option, the used format namespace(s) are to be given. This is the case if the data sets carries additional information as specified by other, particular LCA formats, e.g. of other database networks or LCA softwares.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class PublicationAndOwnership(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    common_dataSetVersion: str = Field(
        ...,
        alias='common:dataSetVersion',
        description="Version number of data set. First two digits refer to major updates, the second two digits to minor revisions and error corrections etc. The third three digits are intended for automatic and internal counting of versions during data set development. Together with the data set's UUID, the 'Data set version' uniquely identifies each data set.",
    )
    common_referenceToPrecedingDataSetVersion: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToPrecedingDataSetVersion',
        description='Last preceding data set, which was replaced by this version. Either a URI of that data set (i.e. an internet address) or its UUID plus version number is given (or both).',
        union_mode='smart',
    )
    common_permanentDataSetURI: AnyUrl | None = Field(
        None,
        alias='common:permanentDataSetURI',
        description="URI (i.e. an internet address) of the original of this data set. [Note: This equally globally unique identifier supports users and software tools to identify and retrieve the original version of a data set via the internet or to check for available updates. The URI must not represent an existing WWW address, but it should be unique and point to the data access point, e.g. by combining the data owner's www path with the data set's UUID, e.g. http://www.mycompany.com/lca/processes/50f12420-8855-12db-b606-0900210c9a66.]",
    )
    common_referenceToOwnershipOfDataSet: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToOwnershipOfDataSet',
        description='"Contact data set" of the person or entity who owns this data set. (Note: this is not necessarily the publisher of the data set.)',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class AdministrativeInformation(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    dataEntryBy: DataEntryBy
    publicationAndOwnership: PublicationAndOwnership
    common_other: str | None = Field(None, alias='common:other')


class ContactDataSet(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    field_xmlns: Literal['http://lca.jrc.it/ILCD/Contact'] = Field(..., alias='@xmlns')
    field_xmlns_common: Literal['http://lca.jrc.it/ILCD/Common'] = Field(
        ..., alias='@xmlns:common'
    )
    field_xmlns_xsi: Literal['http://www.w3.org/2001/XMLSchema-instance'] = Field(
        ..., alias='@xmlns:xsi'
    )
    field_version: Literal['1.1'] = Field(
        ...,
        alias='@version',
        description='Indicates, which version of the ILCD format is used',
    )
    field_xsi_schemaLocation: Literal[
        'http://lca.jrc.it/ILCD/Contact ../../schemas/ILCD_ContactDataSet.xsd'
    ] = Field(..., alias='@xsi:schemaLocation')
    contactInformation: ContactInformation
    administrativeInformation: AdministrativeInformation
    common_other: str | None = Field(None, alias='common:other')


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    contactDataSet: ContactDataSet
    common_other: str | None = Field(None, alias='common:other')
