# generated by datamodel-codegen:
#   filename:  tidas_contacts.json

from __future__ import annotations

from typing import Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class CommonClas(BaseModel):
    field_level: Literal['0'] = Field(..., alias='@level')
    field_classId: str = Field(..., alias='@classId')
    text: str = Field(..., alias='#text')


class CommonClas1(BaseModel):
    field_level: Literal['1'] = Field(..., alias='@level')
    field_classId: str = Field(..., alias='@classId')
    text: str = Field(..., alias='#text')


class CommonClass1(BaseModel):
    pass


class CommonClass(RootModel[list[CommonClas | CommonClas1] | CommonClass1]):
    root: list[CommonClas | CommonClas1] | CommonClass1 = Field(..., union_mode='smart')


CommonClass2 = CommonClas


class CommonClassification(BaseModel):
    """
    Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.
    """

    common_class: CommonClass | CommonClass2 = Field(
        ..., alias='common:class', union_mode='smart'
    )


class ClassificationInformation(BaseModel):
    """
    Hierachical classification of the contact foreseen to be used to structure the contact content of the database. (Note: This entry is NOT required for the identification of the contact data set. It should nevertheless be avoided to use identical names for contacts in the same class.
    """

    common_classification: CommonClassification = Field(
        ...,
        alias='common:classification',
        description='Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.',
    )
    common_other: str | None = Field(None, alias='common:other')


class CASNumber(RootModel[str]):
    root: str = Field(
        ...,
        description='CAS Number, leading zeros are requried.',
        pattern='^[0-9]{2,7}-[0-9]{2}-[0-9]$',
    )


class FT(RootModel[str]):
    root: str = Field(..., description='Free text with an unlimited length.')


class StringMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=500)


class StringMultiLang1(RootModel[list[StringMultiLang1Item]]):
    root: list[StringMultiLang1Item] = Field(
        ..., description='Multi-language string with a maximum length of 500 characters'
    )


class StringMultiLang2(BaseModel):
    """
    Multi-language string with a maximum length of 500 characters
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=500)


class Int5(RootModel[str]):
    root: str = Field(
        ..., description='5-digit integer number', pattern='^(0|[1-9]\\d{0,4})$'
    )


class Int6(RootModel[str]):
    root: str = Field(
        ..., description='6-digit integer number', pattern='^(0|[1-9]\\d{0,5})$'
    )


class LevelType(RootModel[str]):
    root: str = Field(
        ...,
        description='1-digit integer number, must be equal to or greater than 0',
        pattern='^[0-9]$',
    )


class Perc(RootModel[str]):
    root: str = Field(
        ...,
        description='percentage amount',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )


class MatR(RootModel[str]):
    root: str = Field(..., description='Mathematical rule')


class MatV(RootModel[str]):
    root: str = Field(..., description='Mathematical variable or parameter')


class Real(RootModel[str]):
    root: str = Field(
        ...,
        description='38-digit real number',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )


class STMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=1000)


class STMultiLang1(RootModel[list[STMultiLang1Item]]):
    root: list[STMultiLang1Item] = Field(
        ...,
        description='Multi-lang short text with a maximum length of 1000 characters.',
    )


class STMultiLang2(BaseModel):
    """
    Multi-lang short text with a maximum length of 1000 characters.
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text', max_length=1000)


class FTMultiLang1Item(BaseModel):
    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text')


class FTMultiLang1(RootModel[list[FTMultiLang1Item]]):
    root: list[FTMultiLang1Item] = Field(
        ..., description='Multi-lang free text with an unlimited length.'
    )


class FTMultiLang2(BaseModel):
    """
    Multi-lang free text with an unlimited length.
    """

    field_xml_lang: str = Field(..., alias='@xml:lang')
    text: str = Field(..., alias='#text')


class FTMultiLang(RootModel[FTMultiLang1 | FTMultiLang2]):
    root: FTMultiLang1 | FTMultiLang2 = Field(
        ...,
        description='Multi-lang free text with an unlimited length.',
        union_mode='smart',
    )


class GlobalReferenceType1(BaseModel):
    """
    Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.
    """

    field_type: str = Field(..., alias='@type')
    field_refObjectId: str = Field(
        ...,
        alias='@refObjectId',
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )
    field_version: str = Field(..., alias='@version')
    field_uri: str = Field(..., alias='@uri')
    common_shortDescription: STMultiLang1 | STMultiLang2 = Field(
        ...,
        alias='common:shortDescription',
        description='Multi-lang short text with a maximum length of 1000 characters.',
        union_mode='smart',
    )


class GlobalReferenceTypeItem(BaseModel):
    field_type: str = Field(..., alias='@type')
    field_refObjectId: str = Field(
        ...,
        alias='@refObjectId',
        pattern='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
    )
    field_version: str = Field(..., alias='@version')
    field_uri: str = Field(..., alias='@uri')
    common_shortDescription: STMultiLang1 | STMultiLang2 = Field(
        ...,
        alias='common:shortDescription',
        description='Multi-lang short text with a maximum length of 1000 characters.',
        union_mode='smart',
    )


class GIS(RootModel[str]):
    root: str = Field(
        ...,
        description='Global geographical reference in Latitude and LongitudeExamples: "+42.42;-180", "0;0", "13.22 ; -3"',
        pattern='^\\s*[+-]?((90(\\.0+)?)|([0-8]?\\d(\\.\\d+)?))\\s*;\\s*[+-]?((180(\\.0+)?)|((1[0-7]\\d|[0-9]?\\d)(\\.\\d+)?))\\s*$',
    )


class Year(RootModel[int]):
    root: int = Field(..., description='4-digit year', ge=1000, le=9999)


class DataSetInformation(BaseModel):
    common_UUID: str = Field(
        ...,
        alias='common:UUID',
        description="Automatically generated Universally Unique Identifier of this data set. Together with the 'Data set version', the UUID uniquely identifies each data set.",
        pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    )
    common_shortName: StringMultiLang1 | StringMultiLang2 = Field(
        ...,
        alias='common:shortName',
        description="Short name for the contact, that is used for display e.g. of links to this data set (especially in case the full name of the contact is rather long, e.g. 'FAO' for 'Food and Agriculture Organization').",
        union_mode='smart',
    )
    common_name: StringMultiLang1 | StringMultiLang2 = Field(
        ...,
        alias='common:name',
        description='Name of the person, working group, organisation, or database network, which is represented by this contact data set.',
        union_mode='smart',
    )
    classificationInformation: ClassificationInformation = Field(
        ...,
        description='Hierachical classification of the contact foreseen to be used to structure the contact content of the database. (Note: This entry is NOT required for the identification of the contact data set. It should nevertheless be avoided to use identical names for contacts in the same class.',
    )
    contactAddress: STMultiLang1 | STMultiLang2 | None = Field(
        None,
        description="Mail address of the contact; specific for the person, working group, or department. [Note: A general contact point to the organisation is to be given in 'General contact point'.]",
        union_mode='smart',
    )
    email: str | None = Field(
        None,
        description='String with a maximum length of 500 characters. Must have a minimum length of 1.',
        max_length=500,
        min_length=1,
    )
    telephone: str | None = Field(
        None,
        description='String with a maximum length of 500 characters. Must have a minimum length of 1.',
        max_length=500,
        min_length=1,
    )
    telefax: str | None = Field(
        None,
        description='String with a maximum length of 500 characters. Must have a minimum length of 1.',
        max_length=500,
        min_length=1,
    )
    WWWAddress: str | None = Field(
        None,
        description='Web-address of the person, working group, organisation or database network.',
        max_length=1000,
    )
    centralContactPoint: STMultiLang1 | STMultiLang2 | None = Field(
        None,
        description='Alternative address / contact details for the contact. Provides contact information in case e.g. the person or group represented by this contact has left the organisation or changed office/telephone. This alternative contact point can hence contain also a central telephone number, e-mail, www-address etc. of the organisation.',
        union_mode='smart',
    )
    contactDescriptionOrComment: STMultiLang1 | STMultiLang2 | None = Field(
        None,
        description='Free text for additional description of the organisation or person of the contact, such as organisational profile, person responsibilities, etc.',
        union_mode='smart',
    )
    referenceToContact: GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None = (
        Field(
            None,
            description='"Contact data set"s of working groups, organisations or database networks to which EITHER this person or entity OR this database, data set format, or compliance system belongs. [Note: This does not necessarily imply a legally binding relationship, but may also be a voluntary membership.]',
            union_mode='smart',
        )
    )
    referenceToLogo: GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None = (
        Field(
            None,
            description='"Source data set" of the logo of the organisation or source to be used in reports etc.',
            union_mode='smart',
        )
    )
    common_other: str | None = Field(None, alias='common:other')


class ContactInformation(BaseModel):
    dataSetInformation: DataSetInformation
    common_other: str | None = Field(None, alias='common:other')


class DataEntryBy(BaseModel):
    common_timeStamp: AwareDatetime = Field(
        ...,
        alias='common:timeStamp',
        description="Date and time stamp of data set generation, typically an automated entry ('last saved').",
    )
    common_referenceToDataSetFormat: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToDataSetFormat',
        description='"Source data set" of the used version of the ILCD format. If additional data format fields have been integrated into the data set file, using the "namespace" option, the used format namespace(s) are to be given. This is the case if the data sets carries additional information as specified by other, particular LCA formats, e.g. of other database networks or LCA softwares.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class PublicationAndOwnership(BaseModel):
    common_dataSetVersion: str = Field(
        ...,
        alias='common:dataSetVersion',
        description="Version number of data set. First two digits refer to major updates, the second two digits to minor revisions and error corrections etc. The third three digits are intended for automatic and internal counting of versions during data set development. Together with the data set's UUID, the 'Data set version' uniquely identifies each data set.",
    )
    common_referenceToPrecedingDataSetVersion: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem] | None
    ) = Field(
        None,
        alias='common:referenceToPrecedingDataSetVersion',
        description='Last preceding data set, which was replaced by this version. Either a URI of that data set (i.e. an internet address) or its UUID plus version number is given (or both).',
        union_mode='smart',
    )
    common_permanentDataSetURI: AnyUrl | None = Field(
        None,
        alias='common:permanentDataSetURI',
        description="URI (i.e. an internet address) of the original of this data set. [Note: This equally globally unique identifier supports users and software tools to identify and retrieve the original version of a data set via the internet or to check for available updates. The URI must not represent an existing WWW address, but it should be unique and point to the data access point, e.g. by combining the data owner's www path with the data set's UUID, e.g. http://www.mycompany.com/lca/processes/50f12420-8855-12db-b606-0900210c9a66.]",
    )
    common_referenceToOwnershipOfDataSet: (
        GlobalReferenceType1 | list[GlobalReferenceTypeItem]
    ) = Field(
        ...,
        alias='common:referenceToOwnershipOfDataSet',
        description='"Contact data set" of the person or entity who owns this data set. (Note: this is not necessarily the publisher of the data set.)',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class AdministrativeInformation(BaseModel):
    dataEntryBy: DataEntryBy
    publicationAndOwnership: PublicationAndOwnership
    common_other: str | None = Field(None, alias='common:other')


class ContactDataSet(BaseModel):
    field_xmlns: Literal['http://lca.jrc.it/ILCD/Contact'] = Field(..., alias='@xmlns')
    field_xmlns_common: Literal['http://lca.jrc.it/ILCD/Common'] = Field(
        ..., alias='@xmlns:common'
    )
    field_xmlns_xsi: Literal['http://www.w3.org/2001/XMLSchema-instance'] = Field(
        ..., alias='@xmlns:xsi'
    )
    field_version: Literal['1.1'] = Field(
        ...,
        alias='@version',
        description='Indicates, which version of the ILCD format is used',
    )
    field_xsi_schemaLocation: Literal[
        'http://lca.jrc.it/ILCD/Contact ../../schemas/ILCD_ContactDataSet.xsd'
    ] = Field(..., alias='@xsi:schemaLocation')
    contactInformation: ContactInformation
    administrativeInformation: AdministrativeInformation
    common_other: str | None = Field(None, alias='common:other')


class Model(BaseModel):
    contactDataSet: ContactDataSet
    common_other: str | None = Field(None, alias='common:other')
