# generated by datamodel-codegen:
#   filename:  tidas_processes.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel
from tidas_sdk.types.tidas_locations_category import Locations

from tidas_sdk.types.tidas_processes_category import (
    Processes,
    TidasProcessesText
)

from tidas_sdk.types.tidas_data_types import (
    CASNumber,
    FT,
    FTMultiLang,
    GIS,
    GlobalReferenceType,
    GlobalReferenceTypeOrArray,
    Int1,
    Int5,
    Int6,
    LevelType,
    MatR,
    MatV,
    MultiLangItem,
    MultiLangItemST,
    MultiLangItemString,
    Perc,
    Real,
    ST,
    STMultiLang,
    String,
    StringMultiLang,
    UUID,
    Year
)



class CommonClas(BaseModel):
    field_level: Literal['0'] = Field(..., alias='@level')
    field_classId: Processes = Field(..., alias='@classId')
    text: TidasProcessesText = Field(..., alias='#text')


class CommonClas1(BaseModel):
    field_level: Literal['1'] = Field(..., alias='@level')
    field_classId: Processes = Field(..., alias='@classId')
    text: TidasProcessesText = Field(..., alias='#text')


class CommonClas2(BaseModel):
    field_level: Literal['2'] = Field(..., alias='@level')
    field_classId: Processes = Field(..., alias='@classId')
    text: TidasProcessesText = Field(..., alias='#text')


class CommonClas3(BaseModel):
    field_level: Literal['3'] = Field(..., alias='@level')
    field_classId: Processes = Field(..., alias='@classId')
    text: TidasProcessesText = Field(..., alias='#text')


class CommonClass(BaseModel):
    pass


class CommonClassification(BaseModel):
    """
    Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.
    """

    common_class: (
        list[CommonClas | CommonClas1 | CommonClas2 | CommonClas3] | CommonClass
    ) = Field(..., alias='common:class', union_mode='smart')
    common_other: str | None = Field(None, alias='common:other')


class ClassificationInformation(BaseModel):
    """
    Hierarchical or flat classification of the good, service or function that is provided by this life cycle model; typically used to structure database contents in LCA software, among other purposes. (Note: This entry is NOT required for the identification of a Life cycle model, but it should nevertheless be avoided to use identical names for Life cycle model data sets in the same class. The ILCD classifications are defined in the ILCDClassifications.xml file, for common use.)
    """

    common_classification: CommonClassification = Field(
        ...,
        alias='common:classification',
        description='Optional statistical or other classification of the data set. Typically also used for structuring LCA databases.',
    )


class FieldType(Enum):
    Reference_flow_s_ = 'Reference flow(s)'
    Functional_unit = 'Functional unit'
    Other_parameter = 'Other parameter'
    Production_period = 'Production period'


class UncertaintyDistributionType(Enum):
    """
    Defines the kind of uncertainty distribution that is valid for this particular object or parameter.
    """

    undefined = 'undefined'
    log_normal = 'log-normal'
    normal = 'normal'
    triangular = 'triangular'
    uniform = 'uniform'


class TypeOfDataSet(Enum):
    """
    Type of the data set regarding systematic inclusion/exclusion of upstream or downstream processes, transparency and internal (hidden) multi-functionality, and the completeness of modelling.
    """

    Unit_process__single_operation = 'Unit process, single operation'
    Unit_process__black_box = 'Unit process, black box'
    LCI_result = 'LCI result'
    Partly_terminated_system = 'Partly terminated system'
    Avoided_product_system = 'Avoided product system'


class LCIMethodPrinciple(Enum):
    """
    LCI method principle followed in the product system modelling, i.e. regarding using average data (= attributional = non-marginal) or modelling effects in a change-oriented way (= consequential = marginal).
    """

    Attributional = 'Attributional'
    Consequential = 'Consequential'
    Consequential_with_attributional_components = (
        'Consequential with attributional components'
    )
    Not_applicable = 'Not applicable'
    Other = 'Other'


class LCIMethodApproaches(Enum):
    """
    Names briefly the specific approach(es) used in LCI modeling, e.g. allocation, substitution etc. In case of LCI results and Partly terminated system data sets this also covers those applied in the included background system.
    """

    Allocation___market_value = 'Allocation - market value'
    Allocation___gross_calorific_value = 'Allocation - gross calorific value'
    Allocation___net_calorific_value = 'Allocation - net calorific value'
    Allocation___exergetic_content = 'Allocation - exergetic content'
    Allocation___element_content = 'Allocation - element content'
    Allocation___mass = 'Allocation - mass'
    Allocation___volume = 'Allocation - volume'
    Allocation___ability_to_bear = 'Allocation - ability to bear'
    Allocation___marginal_causality = 'Allocation - marginal causality'
    Allocation___physical_causality = 'Allocation - physical causality'
    Allocation___100__to_main_function = 'Allocation - 100% to main function'
    Allocation___other_explicit_assignment = 'Allocation - other explicit assignment'
    Allocation___equal_distribution = 'Allocation - equal distribution'
    Substitution___BAT = 'Substitution - BAT'
    Substitution___average__market_price_correction = (
        'Substitution - average, market price correction'
    )
    Substitution___average__technical_properties_correction = (
        'Substitution - average, technical properties correction'
    )
    Allocation___recycled_content = 'Allocation - recycled content'
    Substitution___recycling_potential = 'Substitution - recycling potential'
    Substitution___average__no_correction = 'Substitution - average, no correction'
    Substitution___specific = 'Substitution - specific'
    Consequential_effects___other = 'Consequential effects - other'
    Not_applicable = 'Not applicable'
    Other = 'Other'


class CompletenessProductModel(Enum):
    """
    Completeness of coverage of relevant product, waste and elementary flows. [Notes: For LCI results and Partly terminated systems this means throughout the underlying product system model. "Relevant" refers to the overall environmental relevance, i.e. for unit processes including the upstream and downstream burdens of product and waste flows.]
    """

    All_relevant_flows_quantified = 'All relevant flows quantified'
    Relevant_flows_missing = 'Relevant flows missing'
    Topic_not_relevant = 'Topic not relevant'
    No_statement = 'No statement'


class FieldType1(Enum):
    Climate_change = 'Climate change'
    Ozone_depletion = 'Ozone depletion'
    Summer_smog = 'Summer smog'
    Eutrophication = 'Eutrophication'
    Acidification = 'Acidification'
    Human_toxicity = 'Human toxicity'
    Freshwater_ecotoxicity = 'Freshwater ecotoxicity'
    Seawater_eco_toxicity = 'Seawater eco-toxicity'
    Terrestric_eco_toxicity = 'Terrestric eco-toxicity'
    Radioactivity = 'Radioactivity'
    Land_use = 'Land use'
    Non_renewable_material_resource_depletion = (
        'Non-renewable material resource depletion'
    )
    Renewable_material_resource_consumption = 'Renewable material resource consumption'
    Non_renewable_primary_energy_depletion = 'Non-renewable primary energy depletion'
    Renewable_primary_energy_consumption = 'Renewable primary energy consumption'
    Particulate_matter_respiratory_inorganics = (
        'Particulate matter/respiratory inorganics'
    )
    Species_depletion = 'Species depletion'
    Noise = 'Noise'


class FieldValue(Enum):
    All_relevant_flows_quantified = 'All relevant flows quantified'
    Relevant_flows_missing = 'Relevant flows missing'
    Topic_not_relevant = 'Topic not relevant'
    No_statement = 'No statement'


class CompletenessElementaryFlows(BaseModel):
    """
    Completeness of the elementary flows in the Inputs and Outputs section of this data set from impact perspective, regarding addressing the individual mid-point problem field / impact category given. The completeness refers to the state-of-the-art of scientific knowledge whether or not an individual elementary flow contributes to the respective mid-point topic in a relevant way, which is e.g. the basis for the ILCD reference elementary flows. [Note: The "Completeness" statement does not automatically mean that related LCIA methods exist or reference the elementary flows of this data set. Hence for direct applicability of existing LCIA methods, check the field "Supported LCIA method data sets".]
    """

    field_type: FieldType1 | None = Field(None, alias='@type')
    field_value: FieldValue | None = Field(None, alias='@value')


class FieldType2(Enum):
    Dependent_internal_review = 'Dependent internal review'
    Independent_internal_review = 'Independent internal review'
    Independent_external_review = 'Independent external review'
    Accredited_third_party_review = 'Accredited third party review'
    Independent_review_panel = 'Independent review panel'
    Not_reviewed = 'Not reviewed'


class FieldName(Enum):
    Raw_data = 'Raw data'
    Unit_process_es___single_operation = 'Unit process(es), single operation'
    Unit_process_es___black_box = 'Unit process(es), black box'
    LCI_results_or_Partly_terminated_system = 'LCI results or Partly terminated system'
    LCIA_results = 'LCIA results'
    Documentation = 'Documentation'
    Life_cycle_inventory_methods = 'Life cycle inventory methods'
    LCIA_results_calculation = 'LCIA results calculation'
    Goal_and_scope_definition = 'Goal and scope definition'


class FieldName1(Enum):
    Validation_of_data_sources = 'Validation of data sources'
    Sample_tests_on_calculations = 'Sample tests on calculations'
    Energy_balance = 'Energy balance'
    Element_balance = 'Element balance'
    Cross_check_with_other_source = 'Cross-check with other source'
    Cross_check_with_other_data_set = 'Cross-check with other data set'
    Expert_judgement = 'Expert judgement'
    Mass_balance = 'Mass balance'
    Compliance_with_legal_limits = 'Compliance with legal limits'
    Compliance_with_ISO_14040_to_14044 = 'Compliance with ISO 14040 to 14044'
    Documentation = 'Documentation'
    Evidence_collection_by_means_of_plant_visits_and_or_interviews = (
        'Evidence collection by means of plant visits and/or interviews'
    )


class CommonMethod(BaseModel):
    """
    Validation method(s) used in the respective "Scope of review".
    """

    field_name: FieldName1 = Field(..., alias='@name')


class CommonMethodItem(BaseModel):
    field_name: FieldName1 = Field(..., alias='@name')


class CommonScope(BaseModel):
    """
    Scope of review regarding which aspects and components of the data set was reviewed or verified. In case of aggregated e.g. LCI results also and on which level of detail (e.g. LCI results only, included unit processes, ...) the review / verification was performed.
    """

    field_name: FieldName = Field(..., alias='@name')
    common_method: CommonMethod | list[CommonMethodItem] = Field(
        ...,
        alias='common:method',
        description='Validation method(s) used in the respective "Scope of review".',
        union_mode='smart',
    )


CommonMethod1 = CommonMethod


CommonMethodItem1 = CommonMethodItem


class CommonScopeItem(BaseModel):
    field_name: FieldName = Field(..., alias='@name')
    common_method: CommonMethod1 | list[CommonMethodItem1] = Field(
        ...,
        alias='common:method',
        description='Validation method(s) used in the respective "Scope of review".',
        union_mode='smart',
    )


class FieldName6(Enum):
    Technological_representativeness = 'Technological representativeness'
    Time_representativeness = 'Time representativeness'
    Geographical_representativeness = 'Geographical representativeness'
    Completeness = 'Completeness'
    Precision = 'Precision'
    Methodological_appropriateness_and_consistency = (
        'Methodological appropriateness and consistency'
    )
    Overall_quality = 'Overall quality'


class FieldValue1(Enum):
    Very_good = 'Very good'
    Good = 'Good'
    Fair = 'Fair'
    Poor = 'Poor'
    Very_poor = 'Very poor'
    Not_evaluated___unknown = 'Not evaluated / unknown'
    Not_applicable = 'Not applicable'


class CommonDataQualityIndicator(BaseModel):
    """
    Data quality indicators serve to provide the reviewed key information on the data set in a defined, computer-readable (and hence searchable) form. This serves to support LCA practitioners to identify/select the highest quality and most appropriate data sets.
    """

    field_name: FieldName6 = Field(..., alias='@name')
    field_value: FieldValue1 = Field(..., alias='@value')


class CommonDataQualityIndicatorItem(BaseModel):
    field_name: FieldName6 = Field(..., alias='@name')
    field_value: FieldValue1 = Field(..., alias='@value')


class CommonDataQualityIndicators(BaseModel):
    """
    Data quality indicators serve to provide the reviewed key information on the data set in a defined, computer-readable (and hence searchable) form. This serves to support LCA practitioners to identify/select the highest quality and most appropriate data sets.
    """

    common_dataQualityIndicator: (
        CommonDataQualityIndicator | list[CommonDataQualityIndicatorItem]
    ) = Field(
        ...,
        alias='common:dataQualityIndicator',
        description='Data quality indicators serve to provide the reviewed key information on the data set in a defined, computer-readable (and hence searchable) form. This serves to support LCA practitioners to identify/select the highest quality and most appropriate data sets.',
        union_mode='smart',
    )


class CommonApprovalOfOverallCompliance(Enum):
    """
    Official approval whether or not and in how far the data set meets all the requirements of the "Compliance system" refered to. This approval should be issued/confirmed by the owner of that compliance system, who is identified via the respective "Contact data set".
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CommonNomenclatureCompliance(Enum):
    """
    Nomenclature compliance of this data set with the respective requirements set by the "compliance system" refered to.
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CommonMethodologicalCompliance(Enum):
    """
    Methodological compliance of this data set with the respective requirements set by the "compliance system" refered to.
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CommonReviewCompliance(Enum):
    """
    Review/Verification compliance of this data set with the respective requirements set by the "compliance system" refered to.
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CommonDocumentationCompliance(Enum):
    """
    Documentation/Reporting compliance of this data set with the respective requirements set by the "compliance system" refered to.
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CommonQualityCompliance(Enum):
    """
    Quality compliance of this data set with the respective requirements set by the "compliance system" refered to.
    """

    Fully_compliant = 'Fully compliant'
    Not_compliant = 'Not compliant'
    Not_defined = 'Not defined'


class CommonWorkflowAndPublicationStatus(Enum):
    """
    Workflow or publication status of data set. Details e.g. of foreseen publication dates should be provided on request by the "Data set owner".
    """

    Working_draft = 'Working draft'
    Final_draft_for_internal_review = 'Final draft for internal review'
    Final_draft_for_external_review = 'Final draft for external review'
    Data_set_finalised__unpublished = 'Data set finalised; unpublished'
    Under_revision = 'Under revision'
    Withdrawn = 'Withdrawn'
    Data_set_finalised__subsystems_published = (
        'Data set finalised; subsystems published'
    )
    Data_set_finalised__entirely_published = 'Data set finalised; entirely published'


class CommonCopyright(Enum):
    """
    Indicates whether or not a copyright on the data set exists. Decided upon by the "Owner of data set". [Note: See also field "Access and use restrictions".]
    """

    true = 'true'
    false = 'false'


class CommonLicenseType(Enum):
    """
    Type of license that applies to the access and use of this data set.
    """

    Free_of_charge_for_all_users_and_uses = 'Free of charge for all users and uses'
    Free_of_charge_for_some_user_types_or_use_types = (
        'Free of charge for some user types or use types'
    )
    Free_of_charge_for_members_only = 'Free of charge for members only'
    License_fee = 'License fee'
    Other = 'Other'


class FunctionType(Enum):
    General_reminder_flow = 'General reminder flow'
    Allocation_reminder_flow = 'Allocation reminder flow'
    System_expansion_reminder_flow = 'System expansion reminder flow'


class ExchangeDirection(Enum):
    Input = 'Input'
    Output = 'Output'


class UncertaintyDistributionType1(Enum):
    undefined = 'undefined'
    log_normal = 'log-normal'
    normal = 'normal'
    triangular = 'triangular'
    uniform = 'uniform'


class DataSourceType(Enum):
    Primary = 'Primary'
    field__90__primary = '> 90% primary'
    Mixed_primary___secondary = 'Mixed primary / secondary'
    Secondary = 'Secondary'


class DataDerivationTypeStatus(Enum):
    Measured = 'Measured'
    Calculated = 'Calculated'
    Estimated = 'Estimated'
    Unknown_derivation = 'Unknown derivation'
    Missing_important = 'Missing important'
    Missing_unimportant = 'Missing unimportant'


class StringMultiLang(RootModel[StringMultiLang]):
    root: StringMultiLang = Field(
        ...,
        description='Multi-language string with a maximum length of 500 characters',
        union_mode='smart',
    )


class GlobalReferenceType(
    RootModel[GlobalReferenceType | list[GlobalReferenceType]]
):
    root: GlobalReferenceType | list[GlobalReferenceType] = Field(
        ...,
        description='Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.',
        union_mode='smart',
    )


class Name(BaseModel):
    """
    General descriptive and specifying name of the process.
    """

    baseName: StringMultiLang = Field(
        ...,
        description='Multi-language string with a maximum length of 500 characters',
        union_mode='smart',
    )
    treatmentStandardsRoutes: StringMultiLang = Field(
        ...,
        description='Multi-language string with a maximum length of 500 characters',
        union_mode='smart',
    )
    mixAndLocationTypes: StringMultiLang = Field(
        ...,
        description='Multi-language string with a maximum length of 500 characters',
        union_mode='smart',
    )
    functionalUnitFlowProperties: StringMultiLang | None = Field(
        None,
        description='Multi-language string with a maximum length of 500 characters',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class ComplementingProcesses(BaseModel):
    referenceToComplementingProcess: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        description='Represents a reference to another dataset or file. Either refObjectId and version, or uri, or both have to be specified.',
        union_mode='smart',
    )


class DataSetInformation(BaseModel):
    """
    General data set information. Section covers all single fields in the ISO/TS 14048 "Process description", which are not part of the other sub-sections. In ISO/TS 14048 no own sub-section is foreseen for these entries.
    """

    common_UUID: str = Field(
        ...,
        alias='common:UUID',
        description='Automatically generated Universally Unique Identifier of this data set. Together with the "Data set version", the UUID uniquely identifies each data set.',
        pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    )
    name: Name = Field(
        ..., description='General descriptive and specifying name of the process.'
    )
    identifierOfSubDataSet: str | None = Field(
        None,
        description='Identifier of a sub-set of a complete process data set. This can be the life cycle stage that a data set covers (such as used in EPDs for modular LCI reporting, with the inventory split up into "resource extraction stage", "production stage", "use stage" and "end-of-life stage"). Or it can be e.g. the type of emission source from which the elementary flows of the Inputs and Outputs stems (e.g. "incineration-related", "transport-related", etc.). Together with the field "Complementing processes" this allows to split up a process data set into a number of clearly identified data sets, each carrying only a part of the inventory and that together represent the complete inventory. Care has to be taken when naming the reference flow, to avoid misinterpretation.',
        max_length=500,
        min_length=1,
    )
    common_synonyms: FTMultiLang | None = Field(
        None,
        alias='common:synonyms',
        description='Synonyms / alternative names / brands of the good, service, or process. Separated by semicolon.',
        union_mode='smart',
    )
    complementingProcesses: ComplementingProcesses | None = None
    classificationInformation: ClassificationInformation = Field(
        ...,
        description='Hierarchical or flat classification of the good, service or function that is provided by this life cycle model; typically used to structure database contents in LCA software, among other purposes. (Note: This entry is NOT required for the identification of a Life cycle model, but it should nevertheless be avoided to use identical names for Life cycle model data sets in the same class. The ILCD classifications are defined in the ILCDClassifications.xml file, for common use.)',
    )
    common_generalComment: FTMultiLang = Field(
        ...,
        alias='common:generalComment',
        description='Free text for general information about the Flow data set. It may contain information about e.g. the use of the substance, good, service or process in a specific technology or industry-context, information sources used, data selection principles etc.',
        union_mode='smart',
    )
    referenceToExternalDocumentation: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        description='"Source data set(s)" of detailed LCA study on the process or product represented by this data set, as well as documents / files with overarching documentative information on technology, geographical and / or time aspects etc. (e.g. basic engineering studies, process simulation results, patents, plant documentation, model behind the parameterisation of the "Mathematical model" section, etc.) (Note: can indirectly reference to digital file.)',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class QuantitativeReference(BaseModel):
    """
    This section names the quantitative reference used for this data set, i.e. the reference to which the inputs and outputs quantiatively relate.
    """

    field_type: FieldType = Field(..., alias='@type')
    referenceToReferenceFlow: str = Field(
        ..., description='6-digit integer number', pattern='^(0|[1-9]\\d{0,5})$'
    )
    functionalUnitOrOther: StringMultiLang | None = Field(
        None,
        description='Multi-language string with a maximum length of 500 characters',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class Time(BaseModel):
    common_referenceYear: int = Field(
        ...,
        alias='common:referenceYear',
        description='Reference year when the emission is assumed to take place, i.e. the start year of the time period for which the impact is modelled. For time-independent models "time independent" should be stated.',
        ge=1000,
        le=9999,
    )
    common_dataSetValidUntil: int | None = Field(
        None,
        alias='common:dataSetValidUntil',
        description='End year of the time period for which the data set is still valid / sufficiently representative. This date also determines when a data set revision / remodelling is required or recommended due to expected relevant changes in environmentally or technically relevant inventory values, including in the background system.',
        ge=1000,
        le=9999,
    )
    common_timeRepresentativenessDescription: FTMultiLang | None = (
        Field(
            None,
            alias='common:timeRepresentativenessDescription',
            description='Description of the valid time span of the data set including information on limited usability within sub-time spans, if any.',
            union_mode='smart',
        )
    )
    common_other: str | None = Field(None, alias='common:other')


class LocationOfOperationSupplyOrProduction(BaseModel):
    """
    Location, country or region the data set represents. [Note 1: This field does not refer to e.g. the country in which a specific site is located that is represented by this data set but to the actually represented country, region, or site. Note 2: Entry can be of type "two-letter ISO 3166 country code" for countries, "seven-letter regional codes" for regions or continents, or "market areas and market organisations", as predefined for the ILCD. Also a name for e.g. a specific plant etc. can be given here (e.g. "FR, Lyon, XY Company, Z Site"; user defined). Note 3: The fact whether the entry refers to production or to consumption / supply has to be stated in the name-field "Mix and location types" e.g. as "Production mix".]
    """

    field_location: Locations = Field(..., alias='@location', union_mode='smart')
    field_latitudeAndLongitude: str | None = Field(
        None,
        alias='@latitudeAndLongitude',
        description='Geographical latitude and longitude reference of "Location" / "Sub-location". For area-type locations (e.g. countries, continents) the field is empty.',
        pattern='^\\s*[+-]?((90(\\.0+)?)|([0-8]?\\d(\\.\\d+)?))\\s*;\\s*[+-]?((180(\\.0+)?)|((1[0-7]\\d|[0-9]?\\d)(\\.\\d+)?))\\s*$',
    )
    descriptionOfRestrictions: FTMultiLang | None = Field(
        None,
        description='Further explanations about additional aspects of the location: e.g. a company and/or site description and address, whether for certain sub-areas within the "Location" the data set is not valid, whether data is only valid for certain regions within the location indicated, or whether certain elementary flows or intermediate product flows are extrapolated from another geographical area.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class SubLocationOfOperationSupplyOrProduction(BaseModel):
    """
    One or more geographical sub-unit(s) of the stated "Location". Such sub-units can be e.g. the sampling sites of a company-average data set, the countries of a region-average data set, or specific sites in a country-average data set. [Note: For single site data sets this field is empty and the site is named in the "Location" field.]
    """

    field_subLocation: Locations | None = Field(
        None, alias='@subLocation', union_mode='smart'
    )
    field_latitudeAndLongitude: str | None = Field(
        None,
        alias='@latitudeAndLongitude',
        description='Geographical latitude and longitude reference of "Location" / "Sub-location". For area-type locations (e.g. countries, continents) the field is empty.',
        pattern='^\\s*[+-]?((90(\\.0+)?)|([0-8]?\\d(\\.\\d+)?))\\s*;\\s*[+-]?((180(\\.0+)?)|((1[0-7]\\d|[0-9]?\\d)(\\.\\d+)?))\\s*$',
    )
    descriptionOfRestrictions: FTMultiLang | None = Field(
        None,
        description='Further explanations about additional aspects of the location: e.g. a company and/or site description and address, whether for certain sub-areas within the "Location" the data set is not valid, whether data is only valid for certain regions within the location indicated, or whether certain elementary flows or intermediate product flows are extrapolated from another geographical area.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class Geography(BaseModel):
    locationOfOperationSupplyOrProduction: LocationOfOperationSupplyOrProduction = (
        Field(
            ...,
            description='Location, country or region the data set represents. [Note 1: This field does not refer to e.g. the country in which a specific site is located that is represented by this data set but to the actually represented country, region, or site. Note 2: Entry can be of type "two-letter ISO 3166 country code" for countries, "seven-letter regional codes" for regions or continents, or "market areas and market organisations", as predefined for the ILCD. Also a name for e.g. a specific plant etc. can be given here (e.g. "FR, Lyon, XY Company, Z Site"; user defined). Note 3: The fact whether the entry refers to production or to consumption / supply has to be stated in the name-field "Mix and location types" e.g. as "Production mix".]',
        )
    )
    subLocationOfOperationSupplyOrProduction: (
        SubLocationOfOperationSupplyOrProduction | None
    ) = Field(
        None,
        description='One or more geographical sub-unit(s) of the stated "Location". Such sub-units can be e.g. the sampling sites of a company-average data set, the countries of a region-average data set, or specific sites in a country-average data set. [Note: For single site data sets this field is empty and the site is named in the "Location" field.]',
    )
    common_other: str | None = Field(None, alias='common:other')


class Technology(BaseModel):
    technologyDescriptionAndIncludedProcesses: FTMultiLang = Field(
        ...,
        description='Description of the technological characteristics including operating conditions of the process or product system. For the latter this includes the relevant upstream and downstream processes included in the data set. Professional terminology should be used.',
        union_mode='smart',
    )
    referenceToIncludedProcesses: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        description='"Process data set(s)" included in this data set, if any and available as separate data set(s).',
        union_mode='smart',
    )
    technologicalApplicability: FTMultiLang | None = Field(
        None,
        description='Description of the intended / possible applications of the good, service, or process. E.g. for which type of products the material, represented by this data set, is used. Examples: "This high purity chemical is used for analytical laboratories only." or "This technical quality bulk chemical is used for large scale synthesis in chemical industry.". Or: "This truck is used only for long-distance transport of liquid bulk chemicals".',
        union_mode='smart',
    )
    referenceToTechnologyPictogramme: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        description='"Source data set" of the pictogramme of the good, service, technogy, plant etc. represented by this data set. For use in graphical user interfaces of LCA software.',
        union_mode='smart',
    )
    referenceToTechnologyFlowDiagrammOrPicture: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        description='"Source data set" of the flow diagramm(s) and/or photo(s) of the good, service, technology, plant etc represented by this data set. For clearer illustration and documentation of data set.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class VariableParameter(BaseModel):
    field_name: str | None = Field(
        None,
        alias='@name',
        description='Name of the variable parameter in the mathematical model.',
    )
    formula: str | None = Field(
        None, description='Formula of the variable parameter in the mathematical model.'
    )
    meanValue: str | None = Field(
        None,
        description='Comment on the variable parameter in the mathematical model.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    minimumValue: str | None = Field(
        None,
        description='Comment on the variable parameter in the mathematical model.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    maximumValue: str | None = Field(
        None,
        description='Comment on the variable parameter in the mathematical model.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    uncertaintyDistributionType: UncertaintyDistributionType | None = Field(
        None,
        description='Defines the kind of uncertainty distribution that is valid for this particular object or parameter.',
    )
    relativeStandardDeviation95In: str | None = Field(
        None,
        description='percentage amount',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )
    comment: StringMultiLang | None = Field(
        None,
        description='Multi-language string with a maximum length of 500 characters',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class MathematicalRelations(BaseModel):
    modelDescription: FTMultiLang | None = Field(
        None,
        description='Description of the model(s) represented in this section of mathematical relations. Can cover information on restrictions, model strenghts and weaknesses, etc. (Note: Also see information provided on the level of the individual formula in field "Comment" and in the general process description in the fields in section "Technology".)',
        union_mode='smart',
    )
    variableParameter: VariableParameter | None = None
    common_other: str | None = Field(None, alias='common:other')


class ProcessInformation(BaseModel):
    """
    Corresponds to the ISO/TS 14048 section "Process description". It comprises the following six sub-sections: 1) "Data set information" for data set identification and overarching information items, 2) "Quantitative reference", 3) "Time", 4) "Geography", 5) "Technology" and 6) "Mathematical relations".
    """

    dataSetInformation: DataSetInformation = Field(
        ...,
        description='General data set information. Section covers all single fields in the ISO/TS 14048 "Process description", which are not part of the other sub-sections. In ISO/TS 14048 no own sub-section is foreseen for these entries.',
    )
    quantitativeReference: QuantitativeReference = Field(
        ...,
        description='This section names the quantitative reference used for this data set, i.e. the reference to which the inputs and outputs quantiatively relate.',
    )
    time: Time
    geography: Geography
    technology: Technology | None = None
    mathematicalRelations: MathematicalRelations | None = None
    common_other: str | None = Field(None, alias='common:other')


class LCIMethodAndAllocation(BaseModel):
    typeOfDataSet: TypeOfDataSet = Field(
        ...,
        description='Type of the data set regarding systematic inclusion/exclusion of upstream or downstream processes, transparency and internal (hidden) multi-functionality, and the completeness of modelling.',
    )
    LCIMethodPrinciple_1: LCIMethodPrinciple | None = Field(
        None,
        alias='LCIMethodPrinciple',
        description='LCI method principle followed in the product system modelling, i.e. regarding using average data (= attributional = non-marginal) or modelling effects in a change-oriented way (= consequential = marginal).',
    )
    deviationsFromLCIMethodPrinciple: FTMultiLang | None = Field(
        None,
        description='Short description of any deviations from the general "LCI method principles" and additional explanations. Refers especially to specific processes/cases where the stated "attributional" or "consequential" approach was not applied. Or where deviations were made from any specific rules for applying the "Consequential with attributional components" approach. A reference to the "Intended application" of the data collection can be made here, too. Allocated co-products may be reported here as well. In case of no (quantitatively relevant) deviations from the LCI method principle, "none" should be stated.',
        union_mode='smart',
    )
    LCIMethodApproaches_1: LCIMethodApproaches | None = Field(
        None,
        alias='LCIMethodApproaches',
        description='Names briefly the specific approach(es) used in LCI modeling, e.g. allocation, substitution etc. In case of LCI results and Partly terminated system data sets this also covers those applied in the included background system.',
    )
    deviationsFromLCIMethodApproaches: FTMultiLang | None = Field(
        None,
        description='Description of relevant deviations from the applied approaches as well as of the relevant specific approaches that were applied, including in an possibly included background system. Further explanations and details of the allocation, substitution and other consequential approaches applied for relevant processes, e.g. how the marginal substitute was identified, year and region of which market prices were used in market allocation, i.e. method, procedure, data/information details. In case of no (result relevant) deviations from the before stated LCI method approaches, and in case of no need for further explanations, "none" is entered.',
        union_mode='smart',
    )
    modellingConstants: FTMultiLang | None = Field(
        None,
        description='Short identification and description of constants applied in LCI modelling other than allocation / substitution, e.g. systematic setting of recycling quota, use of gross or net calorific value, etc.',
        union_mode='smart',
    )
    deviationsFromModellingConstants: FTMultiLang | None = Field(
        None,
        description='Short description of data set specific deviations from the "Modelling constants" if any, including in the possibly included background system.',
        union_mode='smart',
    )
    referenceToLCAMethodDetails: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        description='"Source data set"(s) where the generally used LCA methods including the LCI method principles and specific approaches, the modelling constants details, as well as any other applied methodological conventions are described.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class DataSourcesTreatmentAndRepresentativeness(BaseModel):
    dataCutOffAndCompletenessPrinciples: FTMultiLang = Field(
        ...,
        description='Principles applied in data collection regarding completeness of (also intermediate) product and waste flows and of elementary flows. Examples are: cut-off rules, systematic exclusion of infrastructure, services or auxiliaries, etc. systematic exclusion of air in incineration processes, coling water, etc.',
        union_mode='smart',
    )
    deviationsFromCutOffAndCompletenessPrinciples: (
        FTMultiLang | None
    ) = Field(
        None,
        description='Short description of any deviations from the "Data completeness principles". In case of no (result relevant) deviations, "none" is entered.',
        union_mode='smart',
    )
    dataSelectionAndCombinationPrinciples: FTMultiLang | None = Field(
        None,
        description='Principles applied in data selection and in combination of data from different sources. Includes brief discussion of consistency of data sources regarding data itself, modelling, appropriateness. In case of averaging: Principles and data selection applied in horizontal and / or vertical averaging.',
        union_mode='smart',
    )
    deviationsFromSelectionAndCombinationPrinciples: (
        FTMultiLang | None
    ) = Field(
        None,
        description='Short description of any deviations from the "Data selection and combination principles". In case of no (result relevant) deviations, "none" is entered.',
        union_mode='smart',
    )
    dataTreatmentAndExtrapolationsPrinciples: FTMultiLang | None = (
        Field(
            None,
            description='Principles applied regarding methods, sources, and assumptions done in data adjustment including extrapolations of data from another time period, another geographical area, or another technology.',
            union_mode='smart',
        )
    )
    deviationsFromTreatmentAndExtrapolationPrinciples: (
        FTMultiLang | None
    ) = Field(
        None,
        description='Short description of any deviations from the " Data treatment and extrapolations principles". In case of no (result relevant) deviations, "none" is entered. (Note: If data representative for one "Location" is used for another "Location", its original representativity can be indicated here; see field "Percentage supply or production covered".)',
        union_mode='smart',
    )
    referenceToDataHandlingPrinciples: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        description='"Source data set"(s) of the source(s) in which the data completeness, selection, combination, treatment, and extrapolations principles\' details are described',
        union_mode='smart',
    )
    referenceToDataSource: GlobalReferenceType | list[GlobalReferenceType] = Field(
        ...,
        description='"Source data set"(s) of the source(s) used for deriving/compiling the inventory of this data set e.g. questionnaires, monographies, plant operation protocols, etc. For LCI results and Partly terminated systems the sources for relevant background system data are to be given, too. For parameterised data sets the sources used for the parameterisation / mathematical relations in the section "Mathematical model" are referenced here as well. [Note: If the data set stems from another database or data set publication and is only re-published: identify the origin of a converted data set in "Converted original data set from:" field in section "Data entry by" and its unchanged re-publication in "Unchanged re-publication of:" in the section "Publication and ownership". The data sources used to model a converted or re-published data set are nevertheless to be given here in this field, for transparency reasons.]',
        union_mode='smart',
    )
    percentageSupplyOrProductionCovered: str | None = Field(
        None,
        description='Percentage of the overall supply, consumption, or production of the specific good, service, or technology represented by this data set, in the region/market of the stated "Location". For multi-functional processes the market share of the specific technology is stated. If data that is representative for a process operated in one "Location" is used for another "Location", the entry is \'0\'. The representativity for the original "Location" is documented in the field "Deviation from data treatment and extrapolation principles, explanations".',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )
    annualSupplyOrProductionVolume: StringMultiLang | None = Field(
        None,
        description='Supply / consumption or production volume of the specific good, service, or technology in the region/market of the stated "Location". The market volume is given in absolute numbers per year, in common units, for the stated "Reference year". For multi-fucntional processes the data should be given for all co-functions (good and services).',
        union_mode='smart',
    )
    samplingProcedure: FTMultiLang | None = Field(
        None,
        description='Sampling procedure used for quantifying the amounts of Inputs and Outputs. Possible problems in combining different sampling procedures should be mentioned.',
        union_mode='smart',
    )
    dataCollectionPeriod: StringMultiLang | None = Field(
        None,
        description='Date(s) or time period(s) when the data was collected. Note that this does NOT refer to e.g. the publication dates of papers or books from which the data may stem, but to the original data collection period.',
        union_mode='smart',
    )
    uncertaintyAdjustments: FTMultiLang | None = Field(
        None,
        description='Description of methods, sources, and assumptions made in uncertainty adjustment. [Note: For data sets where the additional uncertainty due to lacking representativeness has been included in the quantified uncertainty values, this field also reports the original representativeness, the additional uncertainty, and the procedure by which the overall uncertainty was assessed or calculated.]',
        union_mode='smart',
    )
    useAdviceForDataSet: FTMultiLang | None = Field(
        None,
        description='Specific methodological advice for data set users that requires attention. E.g. on inclusion/exclusion of recycling e.g. in material data sets, specific use phase behavior to be modelled, and other methodological advices. See also field "Technological applicability".',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class Completeness(BaseModel):
    completenessProductModel: CompletenessProductModel | None = Field(
        None,
        description='Completeness of coverage of relevant product, waste and elementary flows. [Notes: For LCI results and Partly terminated systems this means throughout the underlying product system model. "Relevant" refers to the overall environmental relevance, i.e. for unit processes including the upstream and downstream burdens of product and waste flows.]',
    )
    referenceToSupportedImpactAssessmentMethods: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        description='"LCIA methods data sets" that can be applied to the elementary flows in the Inputs and Outputs section, i.e. ALL these flows are referenced by the respective LCIA method data set (if they are of environmental relevance and a characterisation factor is defined for the respective flow). [Note: Applicability is not given if the inventoty contains some elementary flows with the same meaning as referenced in the LCIA method data set but in a different nomenclature (and hence carry no characterisation factor), or if the flows are sum indicators or flow groups that are addressed differently in the LCIA method data set.]',
        union_mode='smart',
    )
    completenessElementaryFlows: CompletenessElementaryFlows | None = Field(
        None,
        description='Completeness of the elementary flows in the Inputs and Outputs section of this data set from impact perspective, regarding addressing the individual mid-point problem field / impact category given. The completeness refers to the state-of-the-art of scientific knowledge whether or not an individual elementary flow contributes to the respective mid-point topic in a relevant way, which is e.g. the basis for the ILCD reference elementary flows. [Note: The "Completeness" statement does not automatically mean that related LCIA methods exist or reference the elementary flows of this data set. Hence for direct applicability of existing LCIA methods, check the field "Supported LCIA method data sets".]',
    )
    completenessOtherProblemField: FTMultiLang | None = Field(
        None,
        description='Completeness of coverage of elementary flows that contribute to other problem fields that are named here as free text, preferably using the same terminology as for the specified environmental problems.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class Review(BaseModel):
    """
    Type of review that has been performed regarding independency and type of review process.
    """

    field_type: FieldType2 = Field(..., alias='@type')
    common_scope: CommonScope | list[CommonScopeItem] | None = Field(
        None,
        alias='common:scope',
        description='Scope of review regarding which aspects and components of the data set was reviewed or verified. In case of aggregated e.g. LCI results also and on which level of detail (e.g. LCI results only, included unit processes, ...) the review / verification was performed.',
        union_mode='smart',
    )
    common_dataQualityIndicators: CommonDataQualityIndicators | None = Field(
        None,
        alias='common:dataQualityIndicators',
        description='Data quality indicators serve to provide the reviewed key information on the data set in a defined, computer-readable (and hence searchable) form. This serves to support LCA practitioners to identify/select the highest quality and most appropriate data sets.',
    )
    common_reviewDetails: FTMultiLang | None = Field(
        None,
        alias='common:reviewDetails',
        description='Summary of the review. All the following items should be explicitly addressed: Representativeness, completeness, and precision of Inputs and Outputs for the process in its documented location, technology and time i.e. both completeness of technical model (product, waste, and elementary flows) and completeness of coverage of the relevant problem fields (environmental, human health, resource use) for this specific good, service, or process. Plausibility of data. Correctness and appropriateness of the data set documentation. Appropriateness of system boundaries, cut-off rules, LCI modelling choices such as e.g. allocation, consistency of included processes and of LCI methodology. If the data set comprises pre-calculated LCIA results, the correspondence of the Input and Output elementary flows (including their geographical validity) with the applied LCIA method(s) should be addressed by the reviewer. An overall quality statement on the data set may be included here.',
        union_mode='smart',
    )
    common_referenceToNameOfReviewerAndInstitution: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToNameOfReviewerAndInstitution',
        description='"Contact data set" of reviewer. The full name of reviewer(s) and institution(s) as well as a contact address and/or email should be provided in that contact data set.',
        union_mode='smart',
    )
    common_otherReviewDetails: FTMultiLang | None = Field(
        None,
        alias='common:otherReviewDetails',
        description='Further information from the review process, especially comments received from third parties once the data set has been published or additional reviewer comments from an additional external review.',
        union_mode='smart',
    )
    common_referenceToCompleteReviewReport: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToCompleteReviewReport',
        description='"Source data set" of the complete review report.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class Validation(BaseModel):
    """
    Review information on LCIA method.
    """

    review: Review = Field(
        ...,
        description='Type of review that has been performed regarding independency and type of review process.',
    )
    common_other: str | None = Field(None, alias='common:other')


class Compliance(BaseModel):
    """
    One compliance declaration. Multiple declarations may be provided.
    """

    common_referenceToComplianceSystem: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToComplianceSystem',
        description='"Source data set" of the "Compliance system" that is declared to be met by the data set.',
        union_mode='smart',
    )
    common_approvalOfOverallCompliance: CommonApprovalOfOverallCompliance = Field(
        ...,
        alias='common:approvalOfOverallCompliance',
        description='Official approval whether or not and in how far the data set meets all the requirements of the "Compliance system" refered to. This approval should be issued/confirmed by the owner of that compliance system, who is identified via the respective "Contact data set".',
    )
    common_nomenclatureCompliance: CommonNomenclatureCompliance = Field(
        ...,
        alias='common:nomenclatureCompliance',
        description='Nomenclature compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_methodologicalCompliance: CommonMethodologicalCompliance = Field(
        ...,
        alias='common:methodologicalCompliance',
        description='Methodological compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_reviewCompliance: CommonReviewCompliance = Field(
        ...,
        alias='common:reviewCompliance',
        description='Review/Verification compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_documentationCompliance: CommonDocumentationCompliance = Field(
        ...,
        alias='common:documentationCompliance',
        description='Documentation/Reporting compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_qualityCompliance: CommonQualityCompliance = Field(
        ...,
        alias='common:qualityCompliance',
        description='Quality compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_other: str | None = Field(None, alias='common:other')


class Compliance1Item(BaseModel):
    common_referenceToComplianceSystem: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToComplianceSystem',
        description='"Source data set" of the "Compliance system" that is declared to be met by the data set.',
        union_mode='smart',
    )
    common_approvalOfOverallCompliance: CommonApprovalOfOverallCompliance = Field(
        ...,
        alias='common:approvalOfOverallCompliance',
        description='Official approval whether or not and in how far the data set meets all the requirements of the "Compliance system" refered to. This approval should be issued/confirmed by the owner of that compliance system, who is identified via the respective "Contact data set".',
    )
    common_nomenclatureCompliance: CommonNomenclatureCompliance = Field(
        ...,
        alias='common:nomenclatureCompliance',
        description='Nomenclature compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_methodologicalCompliance: CommonMethodologicalCompliance = Field(
        ...,
        alias='common:methodologicalCompliance',
        description='Methodological compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_reviewCompliance: CommonReviewCompliance = Field(
        ...,
        alias='common:reviewCompliance',
        description='Review/Verification compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_documentationCompliance: CommonDocumentationCompliance = Field(
        ...,
        alias='common:documentationCompliance',
        description='Documentation/Reporting compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_qualityCompliance: CommonQualityCompliance = Field(
        ...,
        alias='common:qualityCompliance',
        description='Quality compliance of this data set with the respective requirements set by the "compliance system" refered to.',
    )
    common_other: str | None = Field(None, alias='common:other')


class Compliance1(RootModel[list[Compliance1Item]]):
    root: list[Compliance1Item] = Field(
        ...,
        description='One compliance declaration. Multiple declarations may be provided.',
        min_length=1,
    )


class ComplianceDeclarations(BaseModel):
    """
    Statements on compliance of several data set aspects with compliance requirements as defined by the referenced compliance system (e.g. an EPD scheme, handbook of a national or international data network such as the ILCD, etc.).
    """

    compliance: Compliance | Compliance1 = Field(
        ...,
        description='One compliance declaration. Multiple declarations may be provided.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class ModellingAndValidation(BaseModel):
    LCIMethodAndAllocation_1: LCIMethodAndAllocation = Field(
        ..., alias='LCIMethodAndAllocation'
    )
    dataSourcesTreatmentAndRepresentativeness: (
        DataSourcesTreatmentAndRepresentativeness | None
    ) = None
    completeness: Completeness | None = None
    validation: Validation = Field(
        ..., description='Review information on LCIA method.'
    )
    complianceDeclarations: ComplianceDeclarations = Field(
        ...,
        description='Statements on compliance of several data set aspects with compliance requirements as defined by the referenced compliance system (e.g. an EPD scheme, handbook of a national or international data network such as the ILCD, etc.).',
    )
    common_other: str | None = Field(None, alias='common:other')


class CommonCommissionerAndGoal(BaseModel):
    """
    Basic information about goal and scope of the data set.
    """

    common_referenceToCommissioner: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToCommissioner',
        description='"Contact data set" of the commissioner / financing party of the data collection / compilation and of the data set modelling. For groups of commissioners, each single organisation should be named. For data set updates and for direct use of data from formerly commissioned studies, also the original commissioner should be named.',
        union_mode='smart',
    )
    common_project: StringMultiLang | None = Field(
        None,
        alias='common:project',
        description='Extract of the information items linked to goal and scope of LCIA method modeling.',
        union_mode='smart',
    )
    common_intendedApplications: FTMultiLang = Field(
        ...,
        alias='common:intendedApplications',
        description='Documentation of the intended application(s) of data collection and data set modelling. This indicates / includes information on the level of detail, the specifidity, and the quality ambition in the effort.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class DataGenerator(BaseModel):
    """
    Expert(s), that compiled and modelled the data set as well as internal administrative information linked to the data generation activity.
    """

    common_referenceToPersonOrEntityGeneratingTheDataSet: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToPersonOrEntityGeneratingTheDataSet',
        description='"Contact data set" of the person(s), working group(s), organisation(s) or database network, that generated the data set, i.e. being responsible for its correctness regarding methods, inventory, and documentation.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class DataEntryBy(BaseModel):
    """
    Staff or entity, that documented the generated data set, entering the information into the database; plus administrative information linked to the data entry activity.
    """

    common_timeStamp: AwareDatetime = Field(
        ...,
        alias='common:timeStamp',
        description='Date and time format acc. to ISO 8601',
    )
    common_referenceToDataSetFormat: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToDataSetFormat',
        description='"Source data set" of the used version of the ILCD format. If additional data format fields have been integrated into the data set file, using the "namespace" option, the used format namespace(s) are to be given. This is the case if the data sets carries additional information as specified by other, particular LCA formats, e.g. of other database networks or LCA softwares.',
        union_mode='smart',
    )
    common_referenceToConvertedOriginalDataSetFrom: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToConvertedOriginalDataSetFrom',
        description='"Source data set" of the database or data set publication from which this data set has been obtained by conversion. This can cover e.g. conversion to a different format, applying a different nomenclature, mapping of flow names, conversion of units, etc. This may however not have changed or re-modeled the Inputs and Outputs, i.e. obtaining the same LCIA results. This entry is required for converted data sets stemming originally from other LCA databases (e.g. when re-publishing data from IISI, ILCD etc. databases). [Note: Identically re-published data sets are identied in the field "Unchanged re-publication of:" in the section "Publication and Ownership".]',
        union_mode='smart',
    )
    common_referenceToPersonOrEntityEnteringTheData: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToPersonOrEntityEnteringTheData',
        description='"Contact data set" of the responsible person or entity that has documented this data set, i.e. entered the data and the descriptive information.',
        union_mode='smart',
    )
    common_referenceToDataSetUseApproval: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToDataSetUseApproval',
        description='"Source data set": Names exclusively the producer or operator of the good, service or technology represented by this data set, which officially has approved this data set in all its parts. In case of nationally or internationally averaged data sets, this will be the respective business association. If no official approval has been given, the entry "No official approval by producer or operator" is to be entered and the reference will point to an empty "Contact data set". [Notes: The producer or operator may only be named here, if a written approval of this data set was given. A recognition of this data set by any other organisation then the producer/operator of the good, service, or process is not to be stated here, but as a "review" in the validation section.]',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class PublicationAndOwnership(BaseModel):
    """
    Information related to publication and version management of the data set including copyright and access restrictions.
    """

    common_dateOfLastRevision: AwareDatetime | None = Field(
        None,
        alias='common:dateOfLastRevision',
        description='Date when the data set was revised for the last time, typically manually set.',
    )
    common_dataSetVersion: str = Field(
        ...,
        alias='common:dataSetVersion',
        description='Version number of data set. First two digits refer to major updates, the second two digits to minor revisions and error corrections etc. The third three digits are intended for automatic and internal counting of versions during data set development. Together with the data set\'s UUID, the "Data set version" uniquely identifies each data set.',
    )
    common_referenceToPrecedingDataSetVersion: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToPrecedingDataSetVersion',
        description='Last preceding data set, which was replaced by this version. Either a URI of that data set (i.e. an internet address) or its UUID plus version number is given (or both).',
        union_mode='smart',
    )
    common_permanentDataSetURI: AnyUrl = Field(
        ...,
        alias='common:permanentDataSetURI',
        description="URI (i.e. an internet address) of the original of this data set. [Note: This equally globally unique identifier supports users and software tools to identify and retrieve the original version of a data set via the internet or to check for available updates. The URI must not represent an existing WWW address, but it should be unique and point to the data access point, e.g. by combining the data owner's www path with the data set's UUID, e.g. http://www.mycompany.com/lca/processes/50f12420-8855-12db-b606-0900210c9a66.]",
    )
    common_workflowAndPublicationStatus: CommonWorkflowAndPublicationStatus | None = (
        Field(
            None,
            alias='common:workflowAndPublicationStatus',
            description='Workflow or publication status of data set. Details e.g. of foreseen publication dates should be provided on request by the "Data set owner".',
        )
    )
    common_referenceToUnchangedRepublication: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToUnchangedRepublication',
        description='"Source data set" of the publication, in which this data set was published for the first time. [Note: This refers to exactly this data set as it is, without any format conversion, adjustments, flow name mapping, etc. In case this data set was modified/converted, the original source is documented in "Converted original data set from:" in section "Data entry by".]',
        union_mode='smart',
    )
    common_referenceToRegistrationAuthority: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToRegistrationAuthority',
        description='"Contact data set" of the authority that has registered this data set.',
        union_mode='smart',
    )
    common_registrationNumber: str | None = Field(
        None,
        alias='common:registrationNumber',
        description='A unique identifying number for this data set issued by the registration authority.',
        max_length=500,
        min_length=1,
    )
    common_referenceToOwnershipOfDataSet: (
        GlobalReferenceType | list[GlobalReferenceType]
    ) = Field(
        ...,
        alias='common:referenceToOwnershipOfDataSet',
        description='"Contact data set" of the person or entity who owns this data set. (Note: this is not necessarily the publisher of the data set.)',
        union_mode='smart',
    )
    common_copyright: CommonCopyright = Field(
        ...,
        alias='common:copyright',
        description='Indicates whether or not a copyright on the data set exists. Decided upon by the "Owner of data set". [Note: See also field "Access and use restrictions".]',
    )
    common_referenceToEntitiesWithExclusiveAccess: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        alias='common:referenceToEntitiesWithExclusiveAccess',
        description='"Contact data set" of those entities or persons (or groups of these), to which an exclusive access to this data set is granted. Mainly intended to be used in confidentiality management in projects. [Note: See also field "Access and use restrictions".]',
        union_mode='smart',
    )
    common_licenseType: CommonLicenseType = Field(
        ...,
        alias='common:licenseType',
        description='Type of license that applies to the access and use of this data set.',
    )
    common_accessRestrictions: FTMultiLang | None = Field(
        None,
        alias='common:accessRestrictions',
        description='Access restrictions / use conditions for this data set as free text or referring to e.g. license conditions. In case of no restrictions "None" is entered.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class AdministrativeInformation(BaseModel):
    """
    Information on data set management and administration.
    """

    common_commissionerAndGoal: CommonCommissionerAndGoal = Field(
        ...,
        alias='common:commissionerAndGoal',
        description='Basic information about goal and scope of the data set.',
    )
    dataGenerator: DataGenerator | None = Field(
        None,
        description='Expert(s), that compiled and modelled the data set as well as internal administrative information linked to the data generation activity.',
    )
    dataEntryBy: DataEntryBy = Field(
        ...,
        description='Staff or entity, that documented the generated data set, entering the information into the database; plus administrative information linked to the data entry activity.',
    )
    publicationAndOwnership: PublicationAndOwnership = Field(
        ...,
        description='Information related to publication and version management of the data set including copyright and access restrictions.',
    )
    common_other: str | None = Field(None, alias='common:other')


class Allocation(BaseModel):
    """
    specifies one allocation of this exchange (see the attributes of this tag below)
    """

    field_internalReferenceToCoProduct: str | None = Field(
        None,
        alias='@internalReferenceToCoProduct',
        description='Reference to one of the co-products. The applied allocation approach(es), details and and explanations are documented in the fields "LCI method approaches" and "Deviations from LCI method approaches / explanations". [Notes: Applicable only to multifunctional processes. The documented allocated fractions are only applicable when using the data set for attributional modelling and are to be ignored for consequential modeling.]',
        pattern='^(0|[1-9]\\d{0,5})$',
    )
    field_allocatedFraction: str | None = Field(
        None,
        alias='@allocatedFraction',
        description='Fraction (expressed in %) of this Input or Output flow that is foreseen to be allocated to this co-product (recommended allocation). The numbers across the co-products should sum up to 100%.',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )


class Allocations(BaseModel):
    """
    container tag for the specification of allocations if process has more than one reference product. Use only for multifunctional processes.
    """

    allocation: Allocation | None = Field(
        None,
        description='specifies one allocation of this exchange (see the attributes of this tag below)',
    )


class ReferencesToDataSource(BaseModel):
    """
    "Source data set" of data source(s) used for the value of this specific Input or Output, especially if differing from the general data source used for this data set.
    """

    referenceToDataSource: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        description='"Source data set" of data source(s) used for the value of this specific Input or Output, especially if differing from the general data source used for this data set.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class ExchangeItem(BaseModel):
    field_dataSetInternalID: str = Field(
        ...,
        alias='@dataSetInternalID',
        description='6-digit integer number',
        pattern='^(0|[1-9]\\d{0,5})$',
    )
    referenceToFlowDataSet: GlobalReferenceType | list[GlobalReferenceType] = (
        Field(
            ...,
            description='"Flow data set" of this Input or Output.',
            union_mode='smart',
        )
    )
    location: str | None = Field(
        None,
        description='Location where exchange of elementary flow occurs. Used only for those LCIA methods, that make use of this information. This information refers to the entry within the same field in the "Inputs and Outpts" section of the "Process or LCI result data set".',
        max_length=500,
        min_length=1,
    )
    functionType: FunctionType | None = None
    exchangeDirection: ExchangeDirection
    referenceToVariable: str | None = Field(
        None,
        description='Data set internal reference to a variable or parameter name as defined in the section "Mathematical model". The value of this variable or parameter acts as linear multiplier to the value given in the field "Mean amount" to yield the "Resulting amount", which is the final value in the inventory.',
        max_length=500,
        min_length=1,
    )
    meanAmount: str = Field(
        ...,
        description='Mean amount of the Input or Output. Only significant digits of the amount should be stated.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    resultingAmount: str = Field(
        ...,
        description='Final value to be used for calculation of the LCI results and in the product system: It is calculated as the product of the "Mean amount" value times the value of the "Variable". In case that no "Variable" entry is given, the "Resulting amount" is identical to the "Mean amount", i.e. a factor "1" is applied.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    minimumAmount: str | None = Field(
        None,
        description='Minimum amount of the Input or Output in case the uncertainty distribution is uniform or triangular. In case of calculated LCI results and for the aggregated flows in Partly terminated system data sets, the lower end of the 95% likelihood range, i.e. the "2.5% value" can be reported in this field.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    maximumAmount: str | None = Field(
        None,
        description='Maximum amount of the Input or Output in case the uncertainty distribution is uniform or triangular. In case of calculated LCI results and for the aggregated flows in Partly terminated system data sets, the upper end of the 95% likelihood range, i.e. the "97.5% value" can be reported in this field.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    uncertaintyDistributionType: UncertaintyDistributionType1 | None = None
    relativeStandardDeviation95In: str | None = Field(
        None,
        description='The resulting overall uncertainty of the calculated variable value considering uncertainty of measurements, modelling, appropriateness etc. [Notes: For log-normal distribution the square of the geometric standard deviation (SDg^2) is stated. Mean value times SDg^2 equals the 97.5% value (= Maximum value), Mean value divided by SDg^2 equals the 2.5% value (= Minimum value). For normal distribution the doubled standard deviation value (2*SD) is entered. Mean value plus 2*SD equals 97.5% value (= Maximum value), Mean value minus 2*SD equals 2.5% value (= Minimum value). This data field remains empty when uniform or triangular uncertainty distribution is applied.]',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )
    allocations: Allocations | None = Field(
        None,
        description='container tag for the specification of allocations if process has more than one reference product. Use only for multifunctional processes.',
    )
    dataSourceType: DataSourceType | None = None
    dataDerivationTypeStatus: DataDerivationTypeStatus
    referencesToDataSource: ReferencesToDataSource | None = Field(
        None,
        description='"Source data set" of data source(s) used for the value of this specific Input or Output, especially if differing from the general data source used for this data set.',
    )
    generalComment: StringMultiLang | None = Field(
        None,
        description='General comment on this specific Input or Output, e.g. commenting on the data sources used and their specific representatuveness etc., on the status of "finalisation" of an entry as workflow information, etc.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


class Exchanges(BaseModel):
    exchange: list[ExchangeItem]
    common_other: str | None = Field(None, alias='common:other')


class LCIAResult(BaseModel):
    referenceToLCIAMethodDataSet: (
        GlobalReferenceType | list[GlobalReferenceType] | None
    ) = Field(
        None,
        description='"LCIA method data set" applied to calculate the LCIA results.',
        union_mode='smart',
    )
    meanAmount: str = Field(
        ...,
        description='Mean amount of the Input or Output. Only significant digits of the amount should be stated.',
        pattern='[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([Ee][+-]?\\d+)?$',
    )
    uncertaintyDistributionType: UncertaintyDistributionType1 | None = None
    relativeStandardDeviation95In: str | None = Field(
        None,
        description='The resulting overall uncertainty of the calculated variable value considering uncertainty of measurements, modelling, appropriateness etc. [Notes: For log-normal distribution the square of the geometric standard deviation (SDg^2) is stated. Mean value times SDg^2 equals the 97.5% value (= Maximum value), Mean value divided by SDg^2 equals the 2.5% value (= Minimum value). For normal distribution the doubled standard deviation value (2*SD) is entered. Mean value plus 2*SD equals 97.5% value (= Maximum value), Mean value minus 2*SD equals 2.5% value (= Minimum value). This data field remains empty when uniform or triangular uncertainty distribution is applied.]',
        pattern='^(100(\\.0{1,3})?|([0-9]|[1-9][0-9])(\\.\\d{1,3})?)$',
    )
    generalComment: StringMultiLang | None = Field(
        None,
        description='General comment on this specific Input or Output, e.g. commenting on the data sources used and their specific representatuveness etc., on the status of "finalisation" of an entry as workflow information, etc.',
        union_mode='smart',
    )
    common_other: str | None = Field(None, alias='common:other')


LCIAResult1Item = LCIAResult


class LCIAResult1(RootModel[list[LCIAResult1Item]]):
    root: list[LCIAResult1Item] = Field(..., min_length=1)


class LCIAResults(BaseModel):
    LCIAResult_1: LCIAResult | LCIAResult1 | None = Field(
        None, alias='LCIAResult', union_mode='smart'
    )
    common_other: str | None = Field(None, alias='common:other')


class ProcessDataSet(BaseModel):
    field_xmlns_common: Literal['http://lca.jrc.it/ILCD/Common'] = Field(
        ..., alias='@xmlns:common'
    )
    field_xmlns: Literal['http://lca.jrc.it/ILCD/Process'] = Field(..., alias='@xmlns')
    field_xmlns_xsi: Literal['http://www.w3.org/2001/XMLSchema-instance'] = Field(
        ..., alias='@xmlns:xsi'
    )
    field_version: Literal['1.1'] = Field(..., alias='@version')
    field_locations: Literal['../ILCDLocations.xml'] = Field(..., alias='@locations')
    field_xsi_schemaLocation: str = Field(
        ...,
        alias='@xsi:schemaLocation',
        description='http://lca.jrc.it/ILCD/Process ../../schemas/ILCD_ProcessDataSet.xsd',
    )
    processInformation: ProcessInformation = Field(
        ...,
        description='Corresponds to the ISO/TS 14048 section "Process description". It comprises the following six sub-sections: 1) "Data set information" for data set identification and overarching information items, 2) "Quantitative reference", 3) "Time", 4) "Geography", 5) "Technology" and 6) "Mathematical relations".',
    )
    modellingAndValidation: ModellingAndValidation
    administrativeInformation: AdministrativeInformation = Field(
        ..., description='Information on data set management and administration.'
    )
    exchanges: Exchanges
    LCIAResults_1: LCIAResults | None = Field(None, alias='LCIAResults')
    common_other: str | None = Field(None, alias='common:other')


class Model(BaseModel):
    processDataSet: ProcessDataSet
