# generated by datamodel-codegen:
#   filename:  tidas_locations_category.json

from __future__ import annotations

from pydantic import Field, RootModel


class Model(RootModel[str]):
    root: str = Field(...)
